Use SQPOLL mode
netty/netty pull request #10548
Opened 2020-09-08 08:17 UTC by 1Jo1

Motivation:

0-syscall operation submission, if configured in SQPOLL mode, a kernel thread is created to perform submission queue polling which means that no submission needed, however the cpu usage is higher

Modifications:

-when the kernel thread is idle, we have to wake up 
if the ring tail is changed
-no io_uring_enter(submission) call anymore

Result:

better performance but the cpu usage is higher

2020-09-08 08:25 UTC, 1Jo1 commented
you cannot open/close descriptors in 5.9 as registration of files is required when SQPOLL is enabled but not 5.10, that's why I use 5.10 
if you want to test it you should use kernel (io_uring-5.10)[https://git.kernel.org/pub/scm/linux/kernel/git/axboe/linux-block.git/log/?h=for-5.10/io_uring]

2020-09-08 08:27 UTC, 1Jo1 commented
BTW I had a performance boost of 15% in echo benchmark tests when SQPOLL is active :fire:

2020-09-08 08:28 UTC, 1Jo1 commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/IOUringSubmissionQueue.java
> +        // just a workaround, it seems to fail with
just temporary

2020-09-08 08:33 UTC, 1Jo1 commented
more details about SQPOLL in case if you interested [io_uring mailing list](https://lore.kernel.org/io-uring/CAAss7+pjbh2puVsQTOt7ymKSmbruBZbaOvB8tqfw0z-cMuhJYg@mail.gmail.com/T)

2020-09-08 08:44 UTC, 1Jo1 commented
I think it would be make sense to make  `sq_thread_cpu` configurable which is useful for servers with multiple cpus and `sq_thread_idle` default idle time is 1 Sec
[io_uring_params](https://github.com/axboe/liburing/blob/master/src/include/liburing/io_uring.h#L243)

2020-09-08 11:08 UTC, hyperxpro commented
Would you mind sharing benchmark code?

2020-09-08 11:25 UTC, normanmaurer commented
@hyperxpro we will share some more numbers etc soonish.

2020-09-08 14:44 UTC, njhill reviewed
@1Jo1 nice! I guess in this mode we may want to update the tail pointer after every SQE is added, i.e. better to not batch

2020-09-08 14:44 UTC, njhill commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/IOUringSubmissionQueue.java
> +            if((submitted > 0) && (PlatformDependent.getIntVolatile(kFlagsAddress) & Native.IORING_NEED_WAKEUP) != 0) {
nit: could move `submitted > 0` check outside

2020-09-08 16:42 UTC, 1Jo1 commented
> @1Jo1 nice! I guess in this mode we may want to update the tail pointer after every SQE is added, i.e. better to not batch

@njhill yeah that's true, it's more efficient especially if you want to reduce the latency, I'm gonna test both cases in terms of throughput and latency

2020-09-09 12:57 UTC, normanmaurer commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/IOUringSubmissionQueue.java
> +        // just a workaround, it seems to fail with
Remove comment

2020-09-09 13:00 UTC, 1Jo1 commented
I forgot to mention that SQPOLL in 5.10 root permission is not required anymore, you just need CAP_SYS_NICE privilege

2020-09-11 10:55 UTC, normanmaurer commented
Let's hold back on this till 5.10 was cut.

2020-09-29 18:47 UTC, normanmaurer commented
BTW how we handle writev currently will not work with sqpoll as we can only re-use once the completion event comes back (no stable submission on io_uring_enter(...)).

2020-10-01 07:04 UTC, 1Jo1 commented
@normanmaurer I'm not sure what you mean here, I think it's stable, we do not call io_uring_enter, after you have changed the tail, only then the kernel will see what has been submitted

2020-10-01 07:33 UTC, normanmaurer commented
@1Jo1 as we aren't most of the times call `io_uring_enter` we can not assume we are able to reuse the `IovArray`(as this is only save once we call `io_uring_enter`). We only know for sure once we received the completion event. I have a possible fix for this in the works. Gimme an hour

2020-10-01 07:50 UTC, 1Jo1 commented
@normanmaurer sorry I don't get it.. IovArray should be reuseable as `submissionCallback` will be called after we change the tail

2020-10-01 07:53 UTC, 1Jo1 commented
btw I try to rebase

2020-10-01 07:56 UTC, normanmaurer commented
@1Jo1 thats not correct... we can only re-use once we know the kernel consumed it or we did call `io_uring_enter(...)`. As we not call `io_uring_enter(...)` most of the times here we need to be sure the kernel processed it. Even after we changed the tail the kernel may not consume it for some time so its not safe to reuse until we are sure.

2020-10-01 08:15 UTC, 1Jo1 commented
> @1Jo1 thats not correct... we can only re-use once we know the kernel consumed it or we did call `io_uring_enter(...)`. As we not call `io_uring_enter(...)` most of the times here we need to be sure the kernel processed it. Even after we changed the tail the kernel may not consume it for some time so its not safe to reuse until we are sure.

yes that's true, but that's not related to the SQPOLL implementation, it's general problem, even if we call `io_uring_enter` we don't know when the writev event will be processed, I agree as well we should reused when we will get the completion writev event

2020-10-01 08:31 UTC, normanmaurer commented
@1Jo1 thats incorrect... as soon as you call `io_uring_enter` you can reuse the `struct iovec[]` as the kernel did make a copy of it. That the whole idea of the "stable feature". You cant just reuse the buffers itself.

That said here is the fix https://github.com/netty/netty/pull/10627/

2020-10-01 08:37 UTC, 1Jo1 commented
@normanmaurer ok I didn't know that, I thought it would just do private of the sqe entries, not from the buffer

2020-10-01 08:43 UTC, normanmaurer requested changes

2020-10-01 08:43 UTC, normanmaurer commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/IOUringSubmissionQueue.java
> +        if (!Native.SQPOLL) {
can we just make this a boolean constructor flag per `IOUringEventLoop` ?

2020-10-01 08:43 UTC, normanmaurer commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/IOUringSubmissionQueue.java
> +
nit: `else if ...` (you can merge the two lines

2020-10-01 08:43 UTC, normanmaurer commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/IOUringSubmissionQueue.java
> +                //System.out.println("Wakeup Thread");
nit: remove

2020-10-01 08:43 UTC, normanmaurer commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/Native.java
> +    static final boolean SQPOLL = true;
See above

2020-10-01 08:58 UTC, normanmaurer commented on transport-native-io_uring/src/main/c/netty_io_uring_native.c
> +static jint netty_io_uring_sqPoll(JNIEnv* env, jclass clazz) {
nit... following our style we would call it `netty_io_uring_setup_sqpoll`

2020-10-01 08:59 UTC, normanmaurer commented on transport-native-io_uring/src/main/c/netty_io_uring_native.c
> +static jint netty_io_uring_enter_wakeup(JNIEnv *env, jclass clazz) {
nit... following our style we would call it `netty_io_uring_enter_wakup`

2020-10-26 13:44 UTC, normanmaurer commented
@1Jo1 can you make the requested changes or should I pick it up and push it over the finish line ?

2020-10-26 13:53 UTC, 1Jo1 commented
@normanmaurer I'm working on it, still rebasing...

2020-10-26 15:21 UTC, normanmaurer commented
@1Jo1 all the fun... :D

2020-10-27 17:32 UTC, 1Jo1 commented
SQPOLL non-fixed file support is deferred it to 5.11

2020-10-29 08:50 UTC, normanmaurer commented
Please re-open in https://github.com/netty/netty-incubator-transport-io_uring which is the new home of the io-uring transport

2020-10-29 08:50 UTC, closed without merging