Fix NPE with MqttUnsubAckMessage - regression of MQTT5 support
netty/netty pull request #10557
Opened 2020-09-09 10:31 UTC by paul-lysak

Motivation:

Recent changes for MQTT5 may cause NPE if UNSUBACK message is created with `MqttMessageFactory`
and client code isn't up-to-date.

Modifications:

Added default body in `MqttUnsubAckMessage` constructor if null body is passed, 
added null checks in `encodeUnsubAckMessage`

Result:

`MqttUnsubAckMessage` created with `MqttMessageFactory` doesn't cause NPE
even if null body is supplied.

2020-09-09 10:39 UTC, normanmaurer commented
@netty-bot test this please

2020-09-09 11:06 UTC, franz1981 approved these changes

2020-09-09 13:17 UTC, paul-lysak commented
There were also some class cast exceptions, committed the fix for them here as well.

2020-09-09 13:18 UTC, franz1981 requested changes
Can you add a test here?

2020-09-09 13:20 UTC, paul-lysak commented
> Can you add a test here?

Ok, will do this tomorrow

2020-09-10 09:48 UTC, paul-lysak commented
> Can you add a test here?

Done, added a test

2020-09-10 14:27 UTC, normanmaurer requested changes

2020-09-10 14:27 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttEncoder.java
> +                        message.payload() == null ? 0 : message.payload().unsubscribeReasonCodes().size();
nit: consider storing `payload()` in a local var and use it. There are multiple calls to `message.payload()`

2020-09-10 14:27 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttUnsubAckPayload.java
> +    public static final MqttUnsubAckPayload EMPTY = new MqttUnsubAckPayload();
private ?

2020-09-10 14:28 UTC, normanmaurer commented
@netty-bot test this please ?

2020-09-11 08:51 UTC, chrisvest commented
@netty-bot test this please

2020-09-11 10:55 UTC, normanmaurer approved these changes

2020-09-14 10:04 UTC, merged