Fix #10614 by making UnorderedTPEExecutor.scheduleAtFixedRate run tasks more than once
netty/netty pull request #10659
Opened 2020-10-08 14:11 UTC by chrisvest

Motivation:
All scheduled executors should behave in accordance to their API.
The bug here is that scheduled tasks were not run more than once because we executed the runnables directly, instead of through the provided runnable future.

Modification:
We now run tasks through the provided future, so that when each run completes, the internal state of the task is reset and the ScheduledThreadPoolExecutor is informed of the completion.
This allows the executor to prepare the next run.

Result:
The UnorderedThreadPoolEventExecutor is now able to run scheduled tasks more than once.
Which is what one would expect from the API.

This fixes #10614.

2020-10-10 06:42 UTC, normanmaurer requested changes

2020-10-10 06:42 UTC, normanmaurer commented on common/src/test/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutorTest.java
> +        latch.await();
After this unblocks we should cancel the scheduled task via `future.cancel()`. Also we should shutdown the `executor`.

2020-10-12 12:06 UTC, chrisvest commented
@normanmaurer Addressed your comments. Please take a look.

2020-10-12 12:06 UTC, chrisvest commented
@netty-bot test this please

2020-10-12 12:07 UTC, normanmaurer commented on common/src/test/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutorTest.java
> +            executor.shutdown();
nit: shutdownGracefully() ?

2020-10-12 12:10 UTC, chrisvest commented on common/src/test/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutorTest.java
> +            executor.shutdown();
Alright, done.

2020-10-12 13:14 UTC, chrisvest commented
@netty-bot test this please

2020-10-12 15:03 UTC, normanmaurer approved these changes

2020-10-14 09:09 UTC, merged