Use opcode byte instead of int
netty/netty pull request #10725
Opened 2020-10-23 07:57 UTC by 1Jo1

Motivation:

we should use byte instead of int as the size of opcode is 1 byte

Modification:

use byte instead of int

Result:

we have more space in user_data

2020-10-23 09:04 UTC, franz1981 approved these changes

2020-10-23 09:23 UTC, normanmaurer commented
@netty-bot test this please

2020-10-23 12:08 UTC, normanmaurer requested changes

2020-10-23 12:08 UTC, normanmaurer commented on transport-native-io_uring/src/main/java/io/netty/channel/uring/UserData.java
>          callback.handle(fd, res, flags, op, data);
@1Jo1 we should change the callback handle method to also use byte for the op.

2020-10-25 16:17 UTC, njhill approved these changes
Same comment as @normanmaurer

2020-10-26 12:23 UTC, normanmaurer commented
@netty-bot test this please

2020-10-26 13:43 UTC, merged

2020-10-26 13:43 UTC, normanmaurer commented
I did make the callback fix.