MQTT5: support multiple Subscription ID properties
netty/netty pull request #10734
Opened 2020-10-26 14:50 UTC by paul-lysak

Motivation:

Subscription ID property of the PUBLISH message may be repeated multiple times, which wasn't taken into account when developing `MqttProperties` API.

Modification:

Store Subscription ID properties separately from others - in `MqttProperties.subscriptionIds`. 
Add `MqttProperties.getProperties` method to retrieve properties that may be repeated.
Change internal representation of User Properties for uniformity with Subscription ID - now they're stored in `MqttProperties.userProperties` rather than the common hash map.

Result:

Multiple Subscription ID properties can be set or retrieved.

2020-10-26 14:55 UTC, paul-lysak commented
Also, now I think that introducing `MqttProperties.UserProperties` class to wrap multiple occurrences of `MqttProperties.UserProperty` was a bad idea. If `MqttProperties.listAll` returned a collection of `MqttProperty` instead, `MqttProperties.getProperty` returned first occurence of `UserProperty` and in order to retrieve multiple properties users would need to call `MqttProperties.getProperties` (introduced in this PR) we would have a cleaner API. 
However, the changes are already released and I'm not sure if it's OK to change the way properties behave now.

2020-10-26 15:04 UTC, normanmaurer commented
@netty-bot test this please

@paul-lysak thats right we can not break the API anymore... This ship has sailed :/

2020-10-26 19:22 UTC, normanmaurer requested changes

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +            return "IntegerProperty(" + propertyId + "," + value + ")";
nit: `","` -> `", "` (add space)

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        public static UserProperties fromUserPropertyCollection(Collection<UserProperty> properties) {
does this need to be public ?

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +            return "UserProperty(" + value.key + "," + value.value + ")";
nit: `","` -> `", "`

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        } else if (subscriptionIds == null && userProperties == null) {
nit: you can remove the `else` as you return

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        } else if (props == null && userProperties == null) {
nit: you can remove the `else` as you return

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        } else {
you can remove the `else` as you return before

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +            } else {
nit: you can remove the `else` as you return before

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        } else if (propertyId == MqttPropertyType.SUBSCRIPTION_IDENTIFIER.value) {
nit you can remove the `else`

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +            } else {
nit you can remove the `else`.

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        } else if (propertyId == MqttPropertyType.SUBSCRIPTION_IDENTIFIER.value) {
nit: you can remove the `else` as you return before

2020-10-26 19:22 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        } else {
nit: you can remove the `else` as you return before

2020-10-27 06:59 UTC, paul-lysak commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +        public static UserProperties fromUserPropertyCollection(Collection<UserProperty> properties) {
Not really. Changed to `private`

2020-10-27 07:47 UTC, normanmaurer commented
@netty-bot test this please

2020-10-29 09:25 UTC, chrisvest reviewed
Some small nits, but looks fine.

2020-10-29 09:25 UTC, chrisvest commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttProperties.java
> +     * Some properties (Subscription ID and User Properties) may occur few times,
```suggestion
     * Some properties (Subscription ID and User Properties) may occur multiple times,
```

2020-10-29 09:25 UTC, chrisvest commented on codec-mqtt/src/test/java/io/netty/handler/codec/mqtt/MqttPropertiesTest.java
> +        assertEquals("getProperty User Properties", actualUserProps, expectedUserProps);
The expected value goes before the actual value in `assertEquals`

2020-10-29 09:25 UTC, chrisvest commented on codec-mqtt/src/test/java/io/netty/handler/codec/mqtt/MqttPropertiesTest.java
> +        assertEquals("getProperty User Properties", actualUserProps, expectedUserProps);
📌

2020-10-29 20:34 UTC, chrisvest approved these changes

2020-10-29 20:39 UTC, normanmaurer commented
@netty-bot test this please

2020-10-30 10:17 UTC, normanmaurer approved these changes

2020-10-30 10:17 UTC, merged