fixes #10929
netty/netty pull request #10930
Opened 2021-01-13 15:56 UTC by duke-bartholomew

Motivation:

Exception occurs in the MQTT message builder class (`io.netty.handler.codec.mqtt.MqttMessageBuilders`) when trying to create a message with packetId > 32767

Modification:

refactor the `short` packetId into `int`
as the underlying `MqttMessageIdVariableHeader` of the message treats it as an `int` anyway.

Result:
see unit-test: `MqttMessageBuildersPacketIdTest`

Fixes #10929 .

2021-01-13 17:03 UTC, duke-bartholomew commented
it looks like changing the function signature is not allowed.
I could refactor it so that the builder functions still take a `short`, but in my opinion it makes more sense to align this with the underlying _variable header_ (which takes an `int`) ?

2021-01-13 18:49 UTC, normanmaurer requested changes
```
Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp (default) on project netty-codec-mqtt: There is at least one incompatibility: io.netty.handler.codec.mqtt.MqttMessageBuilders$PubAckBuilder.build():METHOD_RETURN_TYPE_CHANGED,io.netty.handler.codec.mqtt.MqttMessageBuilders$PubAckBuilder.packetId(short):METHOD_REMOVED,io.netty.handler.codec.mqtt.MqttMessageBuilders$SubAckBuilder.packetId(short):METHOD_REMOVED,io.netty.handler.codec.mqtt.MqttMessageBuilders$UnsubAckBuilder.packetId(short):METHOD_REMOVED -> [Help 1]
```

2021-01-13 18:49 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java
> +        public PubAckBuilder packetId(int packetId) {
I think we need to keep the old as well as otherwise it will be a breaking change.

2021-01-13 18:49 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java
> +        public SubAckBuilder packetId(int packetId) {
I think we need to keep the old method as well as otherwise this would be a breaking change

2021-01-13 18:49 UTC, normanmaurer commented on codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java
> +        public UnsubAckBuilder packetId(int packetId) {
I think we need to keep the old method as well as otherwise this would be a breaking change

2021-01-15 20:14 UTC, duke-bartholomew commented
@normanmaurer I changed it back again to take the `packetId` in as a `short`.
But wouldn't it be more generic to actually change that API to work with an `int` (as is done in other mqtt-message methods)?
Now you will always have to convert between `int` and `short` whenever you use these builders.

Anyway, this PR should solve the issue now that a `packetId` > 32767 would result in a negative one when pushed through these builder classes.

2021-01-18 10:31 UTC, normanmaurer commented
@duke-bartholomew I was actually suggesting that you add the `int` methods but keep the short as well.

2021-01-18 12:40 UTC, duke-bartholomew commented
@normanmaurer sorry about the misunderstanding ... new commit adds them back (and deprecates the ones that take in a `short`)

2021-01-18 12:50 UTC, normanmaurer approved these changes

2021-01-19 15:24 UTC, normanmaurer commented
@duke-bartholomew did you sign our ICLA ?

https://netty.io/s/icla

2021-01-20 09:17 UTC, duke-bartholomew commented
> @duke-bartholomew did you sign our ICLA ?
> 
> https://netty.io/s/icla

Yes, I did

2021-01-21 13:40 UTC, merged

2021-01-21 13:40 UTC, normanmaurer commented
@duke-bartholomew thanks a lot