Introduce AsByteBuf interface
netty/netty pull request #11036
Opened 2021-02-24 14:09 UTC by chrisvest

Motivation:
To make it possible to experiment with alternative buffer implementations, we need a way to abstract away the concrete buffers used throughout most of the Netty pipelines, while still having a common currency for doing IO in the end.

Modification:
- Introduce an AsByteBuf interface, that allow arbitrary objects to convert themselves into ByteBuf objects.
- Every place in the code, where we did an instanceof check for ByteBuf, we now do an instanceof check for AsByteBuf.
- ByteBuf itself implements AsByteBuf, and returns itself from the asByteBuf method.

Result:
It is now possible to use Netty with alternative buffer implementations, as long as they can be converted to ByteBuf.
This has been verified elsewhere, with an alternative buffer implementation.

2021-02-24 14:09 UTC, chrisvest commented on buffer/src/main/java/io/netty/buffer/AsByteBuf.java
> +    int readableBytes();
This is only added because it's used in a lot of places. It's convenience but not strictly necessary.

2021-02-24 17:43 UTC, normanmaurer requested changes
Just one nit...

2021-02-24 18:02 UTC, chrisvest commented
@normanmaurer Fixed. Please take a look.

2021-02-24 22:37 UTC, Bennett-Lynch commented
I like the idea of the interface (and have used a similar strategy myself before), but my one nit would be the name: `AsByteBuf`. I don't think this follows the typical Java interface naming convention very well. An interface should usually be a noun or an adjective, not a verb.

That said, I can appreciate `AsByteBuf` for its conciseness, and I'm not sure I have a much better proposal. Perhaps something like `MappableToByteBuf` would be the most correct (and fit in with the JDK8 Stream API terminology), but it's admittedly quite a mouthful.

2021-02-24 22:45 UTC, Bennett-Lynch commented
There is a *lot* of user code that depends directly on `ByteBuf`. I understand that this change should be backwards compatible since `ByteBuf` implements `AsByteBuf` via the identity function, but for anyone wishing to leverage this interface, they will need to update all of their code to migrate to `AsByteBuf`.

This is a tall order, and there's something sort of clunky about referencing `AsByteBuf` when you really just mean `ByteBuf`. Are there any better options? Do we really need this interface if Netty 5 is allowed to just convert `ByteBuf` to an interface?

2021-02-24 23:19 UTC, njhill commented
I had the same hesitation as @Bennett-Lynch about the name. How about `ByteBufLike`?

Also I'm curious if this has any performance implications. Historically it has been much cheaper to check `instanceof` abstract classes than interfaces. IIRC this is why `ByteBuf` was an abstract class in the first place. Maybe related to JVM's class hierarchy analysis. Not sure if this is still the case with latest JVMs or whether it would be a significant factor in any of the places that will be changed...

2021-02-25 10:04 UTC, chrisvest commented
@Bennett-Lynch @njhill I can change the name to `ByteBufLike`, no problem. I'm thinking the existence of this interface might be temporary, as I imagine that we would either switch buffer API or not. I don't think that supporting both APIs concurrently is a state we want to be in long term.

I wrote up and ran a benchmark with Java 11 and it looks like the performance concern with `instanceof` on interfaces is unfounded with the class topology we have:

```java
package io.netty.microbench.internal;

import io.netty.buffer.AsByteBuf;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.microbench.util.AbstractMicrobenchmark;
import io.netty.util.ReferenceCountUtil;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Level;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.Warmup;

import java.util.concurrent.TimeUnit;

@Warmup(iterations = 16, time = 500, timeUnit = TimeUnit.MILLISECONDS)
@Measurement(iterations = 16, time = 500, timeUnit = TimeUnit.MILLISECONDS)
@Fork(5)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Benchmark)
public class InstanceOfBenchmark extends AbstractMicrobenchmark {
    private int counter;

    private volatile Object buffer;

    @Setup(Level.Iteration)
    public void setupTrial() {
        ReferenceCountUtil.release(buffer);
        switch (counter & 3) {
        case 0: buffer = Unpooled.buffer();
        case 1: buffer = Unpooled.wrappedBuffer(new byte[10]);
        case 2: buffer = Unpooled.directBuffer();
        case 3: buffer = Unpooled.compositeBuffer();
        }
        counter++;
    }

    @Benchmark
    public boolean instanceOfInterface() {
        return buffer instanceof AsByteBuf;
    }

    @Benchmark
    public boolean instanceOfAbstractClass() {
        return buffer instanceof ByteBuf;
    }
    
    /*
    Benchmark                                    Mode  Cnt  Score   Error  Units
    InstanceOfBenchmark.instanceOfAbstractClass  avgt   80  2,137 ± 0,012  ns/op
    InstanceOfBenchmark.instanceOfInterface      avgt   80  2,156 ± 0,016  ns/op
     */
}
```

2021-02-25 10:16 UTC, chrisvest commented
`ByteBufConvertible` sounded better.

2021-02-25 11:33 UTC, hepin1989 commented
ByteBufLike

2021-02-25 17:29 UTC, Bennett-Lynch commented
Thanks for the explanation, @chrisvest. So if this interface is meant to be temporary, and we don't have any reason to believe `instanceof` on interfaces has performance implications, and this is on the Netty 5 branch, is there any reason to not just go ahead and convert `ByteBuf` to an interface?

2021-02-25 17:56 UTC, njhill commented
Thanks @chrisvest.

W.r.t. changing `ByteBuf` itself there might still be perf implications around virtual method invocation and JIT inlining behaviour, see the prior details in https://github.com/netty/netty/issues/8534 and https://github.com/netty/netty/pull/1536. Just something to be aware of...

2021-02-25 18:57 UTC, chrisvest commented
@hepin1989 You like the `ByteBufLike` name more? I think "like" is a bit overloaded, and it's not as clear what it means for something to be "like" a `ByteBuf`. I like the `ByteBufConvertible` name because it calls out that the interface is for things that can be converted to `ByteBuf`.

@Bennett-Lynch I think it's better to take one step at a time, but eventually I'd like to end up with using an interface for Netty buffers. See #11024 and https://github.com/netty/netty-incubator-buffer-api/pull/30

@njhill Right, invoking through an interface is more expensive when the method has to be resolved. In this case there is only a single implementation (occasionally two) of `asByteBuf`, so call-sites will be monomorphic or bimorphic and I think the JIT should be able to recognise this. Making `ByteBuf` and interface as it exists now with all its implementations _would_ be a problem, yeah.

2021-02-25 23:35 UTC, Bennett-Lynch commented
I like `ByteBufConvertible`. `ByteBufLike` implies it is something *like* a `ByteBuf` (but probably not a `ByteBuf`).

If `ByteBuf` as an interface is a goal of Netty 5, then it still seems more logical to me to take that direction rather than introduce a temporary interface. However, I'm admittedly not familiar with how people are using or consuming the `master` branch. I was under the impression it was reserved for experimental and ongoing development work.

2021-02-25 23:40 UTC, Bennett-Lynch commented
Nit: I think `ByteBufHolder` could implement the `ByteBufConvertible` interface with a default implementation (is master on JDK8 yet?) of delegating to `ByteBufHolder#content()`. Maybe this minimizes the surface area of needed changes for classes that are already checking `instanceof ByteBufHolder`.

2021-02-26 10:42 UTC, chrisvest commented
@Bennett-Lynch The master branch is on JDK11.

However, a `ByteBufHolder` is not the same as something that can be converted to a `ByteBuf`. A BBC can be converted to its `ByteBuf` form at any point in the pipeline, while a BBH must remain a BBH and handled specially by the pipeline. For instance, this code would break if BBH started extending BBC: https://github.com/netty/netty/pull/11036/files#diff-7a12dfe58a5b91b28843f6e569217a43d6158407f99244e0dcd98224319a9212L235-L245. There are also a number of checks for `DatagramPacket` that, if they were done in a different order, would break on such a change.

2021-02-26 14:02 UTC, normanmaurer commented
@chrisvest lets merge

2021-02-26 14:03 UTC, merged