HttpUtil.getCharset() fails for charset in double-quotes
netty/netty pull request #11373
Opened 2021-06-07 22:14 UTC by NiteshKant

__Motivation__

As described in https://github.com/netty/netty/issues/11370 we should support quoted charset values

__Modification__

Modify `HttpUtil.getCharset(CharSequence contentTypeValue, Charset defaultCharset)` to trim the double-quotes if present.

__Result__
Fixes #11370:  `HttpUtil.getCharset()` now supports quoted charsets.

2021-06-07 22:23 UTC, kashike requested changes

2021-06-07 22:23 UTC, kashike commented on codec-http/src/test/java/io/netty/handler/codec/http/HttpUtilTest.java
> +        HttpUtilTest.this.testGetCharsetUtf8("text/html; charset=\"utf-8\"");
nit: unnecessary full-qualification here

2021-06-07 22:23 UTC, kashike commented on codec-http/src/test/java/io/netty/handler/codec/http/HttpUtilTest.java
> +        HttpUtilTest.this.testGetCharsetUtf8("text/html;charset=\"utf-8\"");
nit: unnecessary full-qualification here

2021-06-08 08:39 UTC, normanmaurer requested changes

2021-06-08 08:39 UTC, normanmaurer commented on codec-http/src/test/java/io/netty/handler/codec/http/HttpUtilTest.java
> +    private void testGetCharsetInvalidQuotes(String contentType) {
nit: static

2021-06-09 09:24 UTC, slandelle approved these changes

2021-06-09 10:36 UTC, normanmaurer approved these changes

2021-06-09 10:37 UTC, merged

2021-06-09 10:37 UTC, normanmaurer commented
@NiteshKant thanks a lot!