Disable Brotli tests on Apple silicon
netty/netty pull request #11397
Opened 2021-06-17 16:27 UTC by alexbudgh

Motivation:

The native module is not yet available on aarch64 Mac thus causing tests in codec/ to fail (specifically all the Brotli ones, since the module could not be loaded).

Modification:

Disable Brotli tests under Mac/aarch64 combo.

Result:

Tests under codec/ now pass under Mac/aarch64.

2021-06-17 17:10 UTC, hyperxpro commented
;/ @normanmaurer Do we really need Brotli4j to support Apple M1 chip?

2021-06-17 17:25 UTC, alexbudgh commented
Not sure I understand the question. It doesn't currently ship an M1 binary, so the tests in netty will fail due to this. This PR disables those tests on that narrow config flavor. Does that make sense?

2021-06-17 17:36 UTC, hyperxpro commented
Yeah, that's completely fine. I didn't compiled Brotli4j for M1 chip. But I wanna know @normanmaurer opinion whether I should M1 chip or not.

2021-06-18 06:01 UTC, trustin commented
It'd be nice brotli4j distributed the binary for Apple Silicon, but I'm fine with disabling the test for it for now.

2021-06-18 06:02 UTC, trustin approved these changes

2021-06-18 06:12 UTC, slandelle commented
@trustin 

> It'd be nice brotli4j distributed the binary for Apple Silicon

Well, as soon as GitHub Actions provides Apple Silicon, see https://github.com/actions/virtual-environments/issues/2187

2021-06-18 06:21 UTC, trustin commented
#11256 adds more test cases that relies on brotli4j. Could you add them in advance?

2021-06-18 08:45 UTC, normanmaurer commented
@alexbudgh @trustin actually I think it would be better if we would use junit5 features for this:

``` java
public boolean isNotSupported() {
    return PlatformDependent.isOsx() && "aarch_64".equals(PlatformDependent.normalizedArch());
}

@DisabledIf(name = "isNotSupported")
public void test() { ... }
```

This way it will also work when trying to run from an IDE.


See https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/condition/DisabledIf.html

2021-06-18 08:46 UTC, normanmaurer requested changes
Please use junit5 features for this :)

2021-07-01 06:26 UTC, normanmaurer commented
Let's close this and pull in https://github.com/netty/netty/pull/11435

2021-07-01 06:26 UTC, closed without merging