Improve `PerMessageDeflateClientExtensionHandler`
netty/netty pull request #11413
Opened 2021-06-23 17:46 UTC by ksmr

Motivation:

The `PerMessageDeflateClientExtensionHandler` has the following strange behaviors currently:

* The `requestedServerNoContext` parameter doesn't actually add the `server_no_context_takeover` parameter to the client offer; instead it depends on the requested server window size.
* The handshake will fail if the server responds with a `server_no_context_takeover` parameter and `requestedServerNoContext` is false. According to RFC 7692 (7.1.1.1) the server may do this, and this means that to cover both cases one needs to use two handshakers in the channel pipeline: one with `requestedServerNoContext = true` and one with `requestedServerNoContext = false`.
* The value of the `server_max_window_bits` parameter in the server response is never checked (should be between 8 and 15). And the value of `client_max_window_bits` is checked only in the branch handling the server window parameter.

Modification:

* Add the `server_no_context_takeover` parameter if `requestedServerNoContext` is true.
* Accept a server handshake response which includes the server no context takeover parameter even if we did not request it.
* Check the values of the client and server window size in their respective branches and fail the handshake if they are out of bounds.

Result:

There will be no need to use two handshakers in the pipeline to be lenient in what handshakes are accepted.

2021-06-24 07:40 UTC, normanmaurer commented
@ksmr can you please also add a unit test ?

2021-06-24 17:59 UTC, ksmr commented
I've added unit tests that are fixed by the changes. :+1:

2021-06-30 10:05 UTC, normanmaurer requested changes

2021-06-30 10:05 UTC, normanmaurer commented on codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateClientExtensionHandshakerTest.java
> +        Map<String, String> parameters;
remove these two and just define them when you actually create the objects

2021-06-30 10:25 UTC, slandelle approved these changes
Great, thanks!

2021-07-02 12:47 UTC, merged

2021-07-02 12:48 UTC, normanmaurer commented
@ksmr thanks a lot!