Ensure DiskFileUpload#toString returns a string that uses the correct deleteOnExit
netty/netty pull request #11628
Opened 2021-08-30 12:11 UTC by violetagg

Motivation:
`DiskFileUpload#toString` should use the value provided when constructing `DiskFileUpload`
and not the default one

Modification:
- `DiskFileUpload#toString` is modified to use the correct `deleteOnExit` value

Result:
`DiskFileUpload#toString` returns a string that uses the correct `deleteOnExit`

2021-08-30 13:38 UTC, chrisvest requested changes

2021-08-30 13:38 UTC, chrisvest commented on codec-http/src/main/java/io/netty/handler/codec/http/multipart/DiskFileUpload.java
> +                (file != null ? file.getAbsolutePath() : "null") + " DefaultDeleteAfter: " + deleteOnExit;
I think the `DefaultDeleteAfter` text should then also be changed to `DeleteAfter`.

2021-08-30 14:02 UTC, violetagg commented on codec-http/src/main/java/io/netty/handler/codec/http/multipart/DiskFileUpload.java
> +                (file != null ? file.getAbsolutePath() : "null") + " DefaultDeleteAfter: " + deleteOnExit;
```suggestion
                (file != null ? file.getAbsolutePath() : "null") + " DeleteAfter: " + deleteOnExit;
```

2021-08-30 14:58 UTC, chrisvest approved these changes

2021-08-31 06:21 UTC, merged

2021-08-31 06:55 UTC, violetagg commented
thanks :grinning: