Remove useless imports and redundant type cast
netty/netty pull request #11639
Opened 2021-09-01 07:29 UTC by skyguard1

Motivation:

There are some redundant imports and unnecessary type cast

Modification:

Remove useless imports and unnecessary type cast

Result:

The code is cleaner than original

2021-09-01 09:53 UTC, hyperxpro approved these changes

2021-09-01 11:15 UTC, chrisvest requested changes

2021-09-01 11:22 UTC, chrisvest approved these changes

2021-09-01 11:23 UTC, skyguard1 commented
@chrisvest Thanks

2021-09-02 17:13 UTC, normanmaurer approved these changes

2021-09-02 17:14 UTC, merged