Add support for mac m1
netty/netty pull request #11666
Opened 2021-09-08 11:24 UTC by normanmaurer

Motivation:

As more and more people switch to a mac m1 we should support it

Modifications:

- Add profiles for cross-compile for mac m1
- Adjust script to finish release

Result:

Mac m1 is supported

2021-09-08 11:40 UTC, chrisvest requested changes

2021-09-08 11:40 UTC, chrisvest commented on resolver-dns-native-macos/pom.xml
> +                  <name>netty_resolver_dns_native_macos_${os.detected.arch}</name>
should this be `${os.detected.arch}` for cross-compilation?

2021-09-08 11:40 UTC, chrisvest commented on resolver-dns-native-macos/pom.xml
> +                  <name>netty_resolver_dns_native_macos_${os.detected.arch}</name>
In the kqueue module this is hard coded to `aarch_64`.

2021-09-08 12:58 UTC, chrisvest approved these changes

2021-09-08 19:45 UTC, merged

2021-12-19 11:51 UTC, YunWZ commented
[ERROR] Failed to execute goal on project netty-handler: Could not resolve dependencies for project io.netty:netty-handler:jar:5.0.0.Final-SNAPSHOT: io.netty:netty-tcnative:jar:osx-aarch_64:2.0.46.Final was not found in https://repo1.maven.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of Central1 has elapsed or updates are forced -> [Help 1]

2021-12-20 21:03 UTC, chrisvest commented
@YunWZ open new issues instead of adding comments to long-closed PRs.

2021-12-21 12:28 UTC, YunWZ commented
> @YunWZ open new issues instead of adding comments to long-closed PRs.

I hava commited a new issue #11941

2021-12-21 12:31 UTC, YunWZ commented
@chrisvest I have commited a new issue #11941