Epoll compiled on GLIBC only supports GLIBC at runtime
netty/netty pull request #11722
Opened 2021-09-29 17:32 UTC by chrisvest

Motivation:
It is possible to run into JVM crashes when our native binaries are compiled for one libc but then linked with another at runtime.
There is no guarantee that their ABIs will be compatible, and this can cause all sorts of trouble.
All our Linux binaries are compiled for GLIBC, so it makes sense to check that any binary compiled for GLIBC also ends up with GLIBC at runtime.
Especially since alternative libc implementations, such as musl, are getting increasingly popular in a containerised/serverless world.

Modification:
Add a check when loading the epoll native library that verifies: if the library was compiled for GLIBC, then we must also have a GLIBC loaded at runtime.
The key is to make this check without making any libc calls in our native code.
We make this check by reading `/proc/self/maps`, which contain paths for all loaded libraries in our process.
GLIBC tends to have paths with a particular pattern to their name, so we look for that.
At compile time, we rely on `__GLIBC__` to determine if the binary is compiled for GLIBC or not.
We cannot check for Musl because they intentionally expose no equivalent define to check for.
By checking for GLIBC specifically, we also end up handling all other alternative libc implementations, and not just Musl.

Result:
Epoll is now reported as not available when running a GLIBC binary on a Musl - or any other alternative libc - based system.
Previously, epoll would be reported as available, but could cause JVM crashes.

This fixes #11701

2021-09-30 06:57 UTC, chrisvest commented
As the builds correctly point out, we can't rely on file names for this check. They are too volatile, and distros are free to name them however they like.

2021-09-30 14:38 UTC, normanmaurer commented on transport-native-epoll/src/main/java/io/netty/channel/epoll/Native.java
> +    private static final boolean skipMuslCheck = SystemPropertyUtil.getBoolean("io.netty.native.musl.check", false);
either we should rename the variable or rename the property

2021-09-30 14:39 UTC, normanmaurer requested changes
one comment

2021-09-30 14:52 UTC, normanmaurer approved these changes

2021-09-30 14:54 UTC, normanmaurer commented on transport-native-epoll/src/main/java/io/netty/channel/epoll/Native.java
> +                    if (muslFound) {
nit: we could just move the whole `throw` in the if block that is contained in the while loop and so get rid of the boolean at all.

2021-10-04 10:08 UTC, normanmaurer commented
@chrisvest ship it!

2021-10-04 13:45 UTC, merged

2021-10-04 21:49 UTC, ninja- commented
does this break environments that ship glibc compat library on top of Alpine, where epoll worked just fine?

2021-10-04 21:49 UTC, ninja- commented
see for example this popular image: https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/12/jre/alpine/Dockerfile.hotspot.releases.full#L34

2021-10-05 09:33 UTC, chrisvest commented
@ninja- Is that on Dockerhub somewhere?

2021-10-05 11:08 UTC, chrisvest commented
It's not clear what image and tag I need to pull to get that one.

2021-10-05 12:33 UTC, chrisvest commented
On `adoptopenjdk/openjdk11:alpine` the glibc-compat shows up as `/usr/glibc-compat/lib/libc.so.6`, so that's not a problem.

2021-10-06 14:57 UTC, ninja- commented
Just checked my prod environment. They are both in memory, so looking at your code logic it would break this environment and disable epoll.

```
/ # cat /proc/82/maps|egrep "musl|libc.so"
7f97b70a7000-7f97b70bc000 r--p 00000000 00:350 10238988                  /lib/ld-musl-x86_64.so.1
7f97b70bc000-7f97b7104000 r-xp 00015000 00:350 10238988                  /lib/ld-musl-x86_64.so.1
7f97b7104000-7f97b713a000 r--p 0005d000 00:350 10238988                  /lib/ld-musl-x86_64.so.1
7f97b713a000-7f97b713b000 r--p 00092000 00:350 10238988                  /lib/ld-musl-x86_64.so.1
7f97b713b000-7f97b713c000 rw-p 00093000 00:350 10238988                  /lib/ld-musl-x86_64.so.1
7f97e9a91000-7f97e9ab6000 r--p 00000000 00:350 10239397                  /usr/glibc-compat/lib/libc.so.6
7f97e9ab6000-7f97e9c01000 r-xp 00025000 00:350 10239397                  /usr/glibc-compat/lib/libc.so.6
7f97e9c01000-7f97e9c4b000 r--p 00170000 00:350 10239397                  /usr/glibc-compat/lib/libc.so.6
7f97e9c4b000-7f97e9c4c000 ---p 001ba000 00:350 10239397                  /usr/glibc-compat/lib/libc.so.6
7f97e9c4c000-7f97e9c4f000 r--p 001ba000 00:350 10239397                  /usr/glibc-compat/lib/libc.so.6
7f97e9c4f000-7f97e9c52000 rw-p 001bd000 00:350 10239397                  /usr/glibc-compat/lib/libc.so.6
```

2021-10-07 09:50 UTC, ninja- commented
Thanks for reverting.
Honestly, I haven't even seen a Java distribution that works on musl, is that even a thing these days?
Every image I've seen had a glibc compatibility layer.

2021-10-07 09:53 UTC, chrisvest commented
I think Java 16 or 17 added support in upstream openjdk. Haven't looked into the details, but there are builds of it available.