Create SimpleChannelPool::notifyConnectChannel method
netty/netty pull request #11860
Opened 2021-11-24 17:59 UTC by diegolovison

Motivation:

A system could have different behavior when connecting to the channel for the first time

Modification:

Create a new method notifyConnectChannel that will be called only the channel is created for the first time

Result:

Projects that are using the Netty Channel Pool can implement custom code during notifyConnect

2021-11-24 18:05 UTC, diegolovison commented
In my scenario I need to do the following:
The promise is called when the listener completes

```java
   protected void notifyConnectChannel(Promise<Channel> promise, Channel channel) {
      channel.closeFuture().addListener((GenericFutureListener<ChannelFuture>) closeFuture -> {
         Channel futureChannel = closeFuture.channel();
         // custom logic
      });
      ChannelKeys.getActivationListener(channel).whenComplete((action, throwable) -> {
         if (throwable != null) {
            promise.setFailure(throwable);
         } else {
            promise.setSuccess(action);
         }
      });
   }
```

2021-11-25 09:27 UTC, normanmaurer requested changes

2021-11-25 09:27 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/pool/SimpleChannelPool.java
> +    protected void notifyConnectChannel(Promise<Channel> promise, Channel channel) {
```suggestion
    protected void notifyChannelConnected(Promise<Channel> promise, Channel channel) {
```

2021-11-25 10:21 UTC, normanmaurer requested changes

2021-12-06 14:07 UTC, normanmaurer commented
@diegolovison ping

2021-12-06 14:40 UTC, diegolovison commented
Hey, there are tests failures from my side even with that change.
I am going to close this PR for now

2021-12-06 14:40 UTC, closed without merging