Fix ArrayIndexOutOfBounds: 39 from PoolArena.findSubpagePoolHead
netty/netty pull request #11939
Opened 2021-12-20 22:42 UTC by chrisvest

Motivation:
We were getting occasional reports of an ArrayIndexOutOfBounds from PoolArena.findSubpagePoolHead, which always happened at index 39.
The sub-page size index array is 39 entries in length, so this access was one past the end.
This should not happen, because a size that *would* compute to index 39, would be a normal-sized allocation (rather than a small one) and thus not use sub-pages at all.
The reason this occurred, is because the "handle" associated with the allocation indicated that it was small, and thus upon freeing we would access the sub-page array, but the specific index was computed from the normalized allocation size, which was "normal" instead of "small".
This happened because of a use-after-free issue in PoolThreadCache, where the entire state of Entry objects were captured prior to return the entry to the recycler *except* for the normCapacity field.
The normCapacity field is what becomes the normSize down the stack, and accessing this field after a recycle could cause the access to race with a concurrent allocation.
So if the allocation was originally small and using sub-pages, then we would capture a sub-page handle, then recycle the entry object, which then got used in a normal-sized allocation, and *then* we read the normCapacity field of this other allocation.

Modification:
The fix is to capture the normCapacity field before calling Entry.recycle() in PoolThreadCache.freeEntry.
A couple of assertions have also been added, to possibly capture bugs like this at an earlier point in the execution.

Result:
We should no longer get this particular ArrayIndexOutOfBoundsException.

This fixes the issues reported by @EzajAnsari and @atanu1991 here: https://github.com/netty/netty/issues/10821#issuecomment-980849785

2021-12-20 23:01 UTC, atanu1991 commented
Thanks a lot @chrisvest 

This def looks promising. If there is a way a test maven version of Netty could be built and uploaded into maven repo, I can test it and let you know.

Unfortunately the tests and jobs are very Meta specific, and its not possible (atleast something that I know of) for it to be reproduced outside.

For context, we use Netty from within Apache Giraph for large scale distributed graph processing.

2021-12-20 23:05 UTC, chrisvest commented
No, you'll have to make your own build from this branch, and replace the JARs in Giraph.

2021-12-20 23:20 UTC, atanu1991 commented
> No, you'll have to make your own build from this branch, and replace the JARs in Giraph.

Cool. Thank you. Any idea when would the next release 4.1.73.Final be with this PR in?

2021-12-21 08:25 UTC, normanmaurer requested changes

2021-12-21 08:25 UTC, normanmaurer commented on buffer/src/main/java/io/netty/buffer/PooledByteBuf.java
> +            }
nit: Why not just use an assert directly ?

```
assert chunk.arena.size2SizeIdx(maxLength) <= chunk.arena.smallMaxSizeIdx : "Allocated small sub-page handle for a buffer size that isn't \"small.\""
```

2021-12-21 08:25 UTC, normanmaurer commented
@chrisvest good catch!

2021-12-21 08:25 UTC, normanmaurer commented
> > No, you'll have to make your own build from this branch, and replace the JARs in Giraph.
> 
> Cool. Thank you. Any idea when would the next release 4.1.73.Final be with this PR in?

Not sure yet... I guess within the next two weeks

2021-12-21 09:12 UTC, EzajAnsari commented
> Motivation: We were getting occasional reports of an ArrayIndexOutOfBounds from PoolArena.findSubpagePoolHead, which always happened at index 39. The sub-page size index array is 39 entries in length, so this access was one past the end. This should not happen, because a size that _would_ compute to index 39, would be a normal-sized allocation (rather than a small one) and thus not use sub-pages at all. The reason this occurred, is because the "handle" associated with the allocation indicated that it was small, and thus upon freeing we would access the sub-page array, but the specific index was computed from the normalized allocation size, which was "normal" instead of "small". This happened because of a use-after-free issue in PoolThreadCache, where the entire state of Entry objects were captured prior to return the entry to the recycler _except_ for the normCapacity field. The normCapacity field is what becomes the normSize down the stack, and accessing this field after a recycle could cause the access to race with a concurrent allocation. So if the allocation was originally small and using sub-pages, then we would capture a sub-page handle, then recycle the entry object, which then got used in a normal-sized allocation, and _then_ we read the normCapacity field of this other allocation.
> 
> Modification: The fix is to capture the normCapacity field before calling Entry.recycle() in PoolThreadCache.freeEntry. A couple of assertions have also been added, to possibly capture bugs like this at an earlier point in the execution.
> 
> Result: We should no longer get this particular ArrayIndexOutOfBoundsException.
> 
> This fixes the issues reported by @EzajAnsari and @atanu1991 here: [#10821 (comment)](https://github.com/netty/netty/issues/10821#issuecomment-980849785)

thanks @chrisvest  and @normanmaurer for the resolution. We will check our application with the patch.

2021-12-21 09:35 UTC, normanmaurer commented
@EzajAnsari @atanu1991 would be cool if you add your use-cases here as well:

https://github.com/netty/netty/wiki/Adopters

2021-12-21 16:09 UTC, chrisvest commented
@normanmaurer Comments addressed. The build failures last time didn't look super relevant, so I'm waiting to see what this build says.

2021-12-22 08:13 UTC, normanmaurer approved these changes

2021-12-22 08:13 UTC, merged

2022-01-03 09:45 UTC, atanu1991 commented
@normanmaurer @chrisvest Is it possible to have a release this week probably? This is blocking a critical release in one of Meta's infrastructure compute engine.

2022-01-03 09:46 UTC, normanmaurer commented
@atanu1991 i can plan one for Thursday

2022-01-04 01:22 UTC, atanu1991 commented
> @atanu1991 i can plan one for Thursday

Thursday sounds good. Thanks a lot. Looking forward to it.

2022-01-06 18:31 UTC, atanu1991 commented
@normanmaurer @chrisvest Could we have a release today please?

2022-01-06 18:52 UTC, normanmaurer commented
Sorry but it will have to wait till early next week… we need to fix a few other things first 

> Am 06.01.2022 um 19:32 schrieb Atanu Ghosh ***@***.***>:
> 
> ﻿
> @normanmaurer @chrisvest Could we have a release today please?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-01-11 18:28 UTC, atanu1991 commented
> Sorry but it will have to wait till early next week… we need to fix a few other things first
> […](#)
> Am 06.01.2022 um 19:32 schrieb Atanu Ghosh ***@***.***>: ﻿ @normanmaurer @chrisvest Could we have a release today please? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Hi @normanmaurer any luck on this?Thanks

2022-01-11 18:29 UTC, normanmaurer commented
Yes tomorrow we will release

2022-01-12 08:01 UTC, atanu1991 commented
@normanmaurer Thanks for the release. I see it here https://github.com/netty/netty/releases/tag/netty-4.1.73.Final

I dont see it in the maven repo yet though https://mvnrepository.com/artifact/io.netty/netty-all
Does it take some time to get published there?

Thanks again!

2022-01-12 14:19 UTC, normanmaurer commented
@atanu1991 its on maven central now (And yes it takes a bit of time to sync)  https://repo1.maven.org/maven2/io/netty/netty-all/4.1.73.Final/

2022-01-14 00:26 UTC, atanu1991 commented
Thank you so much @chrisvest and @normanmaurer 

This indeed fixes the issues and unblocks an internal hi-pri Security related projects at Facebeook (Meta).

Super helpful!

2022-01-14 07:47 UTC, normanmaurer commented
@atanu1991 thanks a lot for closing the loop :)