Fix: Make ByteToMessageDecoder not call read() in channelReadComplete, if no channelRead fired.
netty/netty pull request #11966
Opened 2022-01-02 13:29 UTC by alex-lx

Motivation:

When ByteToMessageDecoder added in channelRead(), the following channelReadComplete() will lead ByteToMessageDecoder to call a read(),
which is not expected.

Modifications:

Add a field variable tracking the state of if ByteToMessageDecoder.channelRead() is fired after the handler is added. And if it was NOT fired, then the next channelReadComplete() would not call read()

Result:

ByteToMessageDecoder will no longer call read() in channelReadComplete() if no channelRead() fired.

Fixes #11965

2022-01-06 10:27 UTC, normanmaurer commented
@alex-lx did you sign our icla yet ?

https://netty.io/s/icla

2022-01-06 10:32 UTC, normanmaurer requested changes

2022-01-06 10:32 UTC, normanmaurer commented on codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java
> +    private boolean selfFiredChannelRead = false;
```suggestion
    private boolean selfFiredChannelRead;
```

2022-01-06 10:32 UTC, normanmaurer commented on codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java
> +    }
This is not needed at all. Please remove

2022-01-06 10:32 UTC, normanmaurer commented on codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java
> +        channel.writeInbound(Unpooled.wrappedBuffer(new byte[]{1}));
```suggestion
        assertFalse(channel.writeInbound(Unpooled.wrappedBuffer(new byte[]{1})));
```

2022-01-06 10:32 UTC, normanmaurer commented on codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java
> +        assertEquals(0, interceptor.readsTriggered);
```suggestion
        assertEquals(0, interceptor.readsTriggered);
        assertNotNull(channel.pipeline().get(FixedLengthFrameDecoder.class));
        assertFalse(channel.finish());
```

2022-01-06 10:39 UTC, normanmaurer requested changes

2022-01-06 10:39 UTC, normanmaurer commented on codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java
> +    }
```suggestion
```

2022-01-06 10:50 UTC, normanmaurer commented on codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java
> +
```suggestion
```

2022-01-06 10:53 UTC, normanmaurer commented on codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java
> +
```suggestion
```

2022-01-06 10:54 UTC, normanmaurer commented on codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java
> +    private static class ReadInterceptingHandler extends ChannelOutboundHandlerAdapter {
```suggestion
    private static final class ReadInterceptingHandler extends ChannelOutboundHandlerAdapter {
```

2022-01-06 14:52 UTC, normanmaurer approved these changes

2022-01-07 02:11 UTC, alex-lx commented
> @alex-lx did you sign our icla yet ?
> 
> https://netty.io/s/icla

Done

2022-01-07 09:27 UTC, merged

2022-01-07 09:27 UTC, normanmaurer commented
@alex-lx thanks a lot!

2022-01-10 16:14 UTC, violetagg commented
@normanmaurer @alex-lx With this PR I'm see an issue with missing `read`. (I'm trying to isolate a test case with vanilla Netty)
The stack is:

```
	at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelReadComplete(CombinedChannelDuplexHandler.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:336)
	at io.netty.channel.CombinedChannelDuplexHandler.channelReadComplete(CombinedChannelDuplexHandler.java:261)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
	at io.netty.handler.logging.LoggingHandler.channelReadComplete(LoggingHandler.java:272)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1415)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

2022-01-10 16:17 UTC, normanmaurer commented
@violetagg keep me posted

2022-01-10 17:43 UTC, violetagg commented
@normanmaurer I'm able to reproduce it with a small change in the Netty examples

https://github.com/violetagg/netty/commit/1ccbd2dfa5978720c5492f6fd9bb6678d2ce3312

1. Start WebSocketServer
2. Start WebSocketClient
3. In the `WebSocketClient` console type `test` for example. You will see that the client is able to receive the close frame.

```
WebSocket Client connected!
test
WebSocket Client received closing
WebSocket Client disconnected!
```

Now revert the changes in `ByteToMessageDecoder` and execute the same scenario. You should be able to see that the client hangs.

```
WebSocket Client connected!
test
```

2022-01-11 03:30 UTC, alex-lx commented
Hi, @violetagg. The future that `WebSocketClientHandshaker#handshake(io.netty.channel.Channel)` returns is resolved after the upgrade request was sent, so the `channel.read()` would just read the handshake's response instead of the websocket frame.
```java
    @Override
    public void channelActive(ChannelHandlerContext ctx) {
        final Channel channel = ctx.channel();
        handshaker.handshake(channel)
                .addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(ChannelFuture future) {
                        // At this moment, the client has just sent the upgrade request, and is waiting server's handshake response.
                        channel.read();
                    }
                });
    }
```
```java
    @Override
    public void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
        Channel ch = ctx.channel();
        if (!handshaker.isHandshakeComplete()) {
            try {
                handshaker.finishHandshake(ch, (FullHttpResponse) msg);
                System.out.println("WebSocket Client connected!");
                // At this moment, the handshake is completed, than we can begin read the websocket frame here
                ch.read();
                handshakeFuture.setSuccess();
            } catch (WebSocketHandshakeException e) {
                System.out.println("WebSocket Client failed to connect");
                handshakeFuture.setFailure(e);
            }
            return;
        }
```

2022-01-11 09:26 UTC, violetagg commented
yeah ... I understand ... this is kind of a change in the behaviour

Anyway I added addition read invocations on my side and now my scenario is working again.

2022-01-11 09:39 UTC, normanmaurer commented
@violetagg yes it is but I think it is more correct. WDYT ?

2022-01-11 09:40 UTC, violetagg commented
yeah go for it