InternalThreadLocalMap.UNSET field should not allow accessed from outside
netty/netty pull request #11992
Opened 2022-01-12 02:49 UTC by laosijikaichele

Motivation:

InternalThreadLocalMap.UNSET field should not allow accessed from outside

Modification:

Moved the class `InternalThreadLocalMap` to package `io.netty.util.concurrent`, and change the access modifier of field `InternalThreadLocalMap.UNSET` to package private

Result:

Fixes #11929.

2022-01-12 07:10 UTC, hyperxpro requested changes
This is a breaking change. We cannot do this.

2022-01-12 07:20 UTC, normanmaurer commented
@hyperxpro this is against `main` so its fine.

2022-01-12 07:32 UTC, hyperxpro commented
Sorry, I didn't see.

2022-01-14 11:21 UTC, normanmaurer commented
I think we can replace this one with https://github.com/netty/netty/pull/11999.

2022-01-14 11:22 UTC, closed without merging