Default logger factory can only be set once
netty/netty pull request #11997
Opened 2022-01-12 23:50 UTC by chrisvest

This is an updated version of #6106

Motivation:

InternalLoggerFactory either sets a default logger factory implementation based on the logging implementations on the classpath, or applications can set a logger factory explicitly.
If applications wait too long to set the logger factory, Netty will have already set a logger factory leading to some objects using one logging implementation and other objets using another logging implementation.
This can happen too if the application tries to set the logger factory twice, which is likely a bug in the application.
Yet, the Javadocs for `InternalLoggerFactory` warn against this saying that `InternalLoggerFactory#setLoggerFactory` "should be called as early as possible and shouldn't be called more than once".
Instead, Netty should guard against this.

Modications:

We replace the logger factory field with an atomic field on which we can do CAS operations to safely guard against it being set twice.
We also add an internal holder class that captures the static interface of `InternalLoggerFactory` that can aid in testing.

Result:

The logging factory can not be set twice, and applications that want to set the logging factory must do it before any Netty classes are initialized (or the default logger factory will be set).

2022-01-13 07:32 UTC, normanmaurer requested changes

2022-01-13 07:32 UTC, normanmaurer commented on common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java
> +            }
Use `Objects.requireNonNull(...)`

2022-01-13 07:32 UTC, normanmaurer commented on common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java
> +                        InternalLoggerFactoryHolder.class, InternalLoggerFactory.class, "reference");
Just use `AtomicReference` there is no need for an updater.

2022-01-13 07:32 UTC, normanmaurer commented on common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java
> + * are loaded. Note that {@link #setDefaultFactory(InternalLoggerFactory)}} can not be invoked more than once.
```suggestion
 * are loaded. <strong>Note that {@link #setDefaultFactory(InternalLoggerFactory)}} can not be invoked more than once.</strong>
```

2022-01-13 16:58 UTC, chrisvest commented
@normanmaurer Addressed.

2022-01-13 17:53 UTC, normanmaurer commented
@chrisvest there seems to be a bug:

https://github.com/netty/netty/runs/4806591398?check_suite_focus=true

2022-01-14 07:40 UTC, normanmaurer approved these changes

2022-01-14 07:40 UTC, merged