InboundHttp2ToHttpAdapter responds with 413 status code
netty/netty pull request #12004
Opened 2022-01-14 14:44 UTC by BrianRothermich

Motivation:
Currently InboundHttp2ToHttpAdapter throws a connection error when it reads a payload that exceeds maxContentLength. This is confusing to clients as the connection is closed with minimal context. Instead servers should respond with an HTTP status code 413 followed by an RST_STREAM frame.

Modifications:
- Created `PayloadTooLargeException` as a subclass of `StreamException`
- `InboundHttp2ToHttpAdapter` throws `PayloadTooLargeException` when it reads a payload that exceeds maxContentLength in bytes
- Modified `Http2ConnectionHandler::onStreamError` to handle `PayloadTooLargeException`s by responding with a status code 413 header frame followed by an RST_FRAME

Result:
When servers using InboundHttp2ToHttpAdapter read a payload exceeding maxContentLength a response with status code 413 will be sent followed by an RST_STREAM frame

Fixes #11994

2022-01-14 18:31 UTC, chrisvest approved these changes

2022-01-18 15:45 UTC, ejona86 requested changes
It's not clear to me why this logic is plumbed through the HTTP/2 stack. It seems like it should be logic local to InboundHttp2ToHttpAdapter. It has access to the Http2Connection.

2022-01-19 00:55 UTC, BrianRothermich commented
@ejona86 are you suggesting that InboundHttp2ToHttpAdapter send the header and reset frames? I don't see a way to do that with just the Http2Connection

2022-01-19 16:10 UTC, ejona86 commented
Hmm... I see. In any case, I still don't think it is appropriate to change the core Http2 logic to respond to a special-cased exception from one listener implementation. The existing HeaderListSizeException that you are mirroring is a core part of the Http2 decoding path, so is quite different.

If fixing this problem _requires_ these changes, I'd favor "just not fix it" vs "add a hack." This stuff is too complicated/brittle already and this is the old API and the broken behavior is very old. InboundHttp2ToHttpAdapter's design is simply broken. If we need something for the frame-based API to have HTTP/1 processors to work nicely, then that's more interesting and worthwhile.

But we do have the option to use a stream error instead of connection error. That will have horrible debuggability on the client, though, but you could maybe have a builder option to pick your poison. The only other option I see is to pass a special message in the pipeline and have the application help with the plumbing of the reply.

It'd be nice if the Http2ConnectionHandler could be passed in, but it can't during the builder because it doesn't exist yet. So there'd be a bit of a dance post-build, but that could be another option.

2022-01-24 21:52 UTC, BrianRothermich commented
@ejona86 thanks for the feedback and suggestions - I hear your concerns with the brittleness of this API. Something for the frame-based API sounds interesting though. In the meantime we have a workaround for this case so I'll close this PR out for now.

2022-01-24 21:52 UTC, closed without merging