Added Fragment-Host declaration to bundles shipping native libs
netty/netty pull request #12018
Opened 2022-01-18 15:11 UTC by MrEasy

Bundles should attach to their host, that contains classes loading the native libraries, so they can be found via Bundle-CL.

Fixes issue #12017

2022-01-18 15:18 UTC, normanmaurer commented
@MrEasy can you sign our ICLA: https://netty.io/s/icla ?

2022-01-19 08:52 UTC, normanmaurer commented
@MrEasy let me know once you signed it

2022-01-19 08:56 UTC, normanmaurer commented
@MrEasy Also we need such a change for resolver-dns-native-macos as well

2022-01-19 09:16 UTC, MrEasy commented
ICLA is currently being checked for, whether I can sign it.
Will have a look at `resolver-dns-native-macos`

2022-01-19 09:36 UTC, MrEasy commented
> ICLA is currently being checked for, whether I can sign it. Will have a look at `resolver-dns-native-macos`

@normanmaurer PR updated with `resolver-dns-native-macos`.

2022-01-19 09:41 UTC, normanmaurer commented on resolver-dns-native-macos/pom.xml
> +                      <Fragment-Host><Fragment-Host>io.netty.transport-classes-kqueue</Fragment-Host></Fragment-Host>
@MrEasy this doesn't look correct

2022-01-19 09:41 UTC, normanmaurer requested changes

2022-01-19 09:41 UTC, normanmaurer commented on resolver-dns-native-macos/pom.xml
> +                      <Fragment-Host><Fragment-Host>io.netty.transport-classes-kqueue</Fragment-Host></Fragment-Host>
@MrEasy this doesn't look correct

2022-01-19 09:46 UTC, MrEasy commented on resolver-dns-native-macos/pom.xml
> +                      <Fragment-Host><Fragment-Host>io.netty.transport-classes-kqueue</Fragment-Host></Fragment-Host>
thx, of course - updated.

2022-01-19 09:46 UTC, MrEasy commented on resolver-dns-native-macos/pom.xml
> +                      <Fragment-Host><Fragment-Host>io.netty.transport-classes-kqueue</Fragment-Host></Fragment-Host>
thx, of course - updated.

2022-01-19 09:50 UTC, normanmaurer approved these changes

2022-01-19 09:52 UTC, normanmaurer requested changes
@MrEasy PTAL

2022-01-19 09:52 UTC, normanmaurer commented on resolver-dns-native-macos/pom.xml
> +                      <Fragment-Host><Fragment-Host>io.netty.resolver-dns-classes-macos</Fragment-Host></Fragment-Host>
```suggestion
                      <Fragment-Host>io.netty.resolver-dns-classes-macos</Fragment-Host>
```

2022-01-19 09:52 UTC, normanmaurer commented on resolver-dns-native-macos/pom.xml
> +                      <Fragment-Host><Fragment-Host>io.netty.resolver-dns-classes-macos</Fragment-Host></Fragment-Host>
```suggestion
                      <Fragment-Host>io.netty.resolver-dns-classes-macos</Fragment-Host>
```

2022-01-19 09:57 UTC, MrEasy commented
> @MrEasy PTAL

uff, not my best performance today....
Thanks again and updated PR to amend in 1 commit

2022-01-19 10:06 UTC, normanmaurer commented
@MrEasy no worries... I know the feeling ... ☕ FTW

2022-01-20 07:50 UTC, MrEasy commented
> @MrEasy let me know once you signed it

@normanmaurer done (on behalf of the company)

2022-01-20 07:54 UTC, merged

2022-01-20 07:54 UTC, normanmaurer commented
@MrEasy Thanks a lot!