Add HTTP-specific TooLongFrameExceptions
netty/netty pull request #12084
Opened 2022-02-08 23:46 UTC by yuzawa-san

Motivation:

I want to examine an HTTP request's decoderResult's cause to determine if my application should return a REQUEST_ENTITY_TOO_LARGE, REQUEST_URI_TOO_LONG, REQUEST_HEADER_FIELDS_TOO_LARGE. Currently the cause is just a plain TooLongFrameException. Although they have different messages, it seems unsafe to examine the messages.

Modifications:

I have extended TooLongFrameException to have TooLongHttpContentException, TooLongHttpHeaderException, and TooLongHttpLineException. Then I updated the sites to throw a specific subclass. Theoretically, more specific subclasses can be added for spdy and websocket, but I held off for now.

Result:

I can examine the decoderResult's cause and properly select how to respond based on what specifically happened. The tests have been update to verify this.

2022-02-09 10:06 UTC, normanmaurer requested changes

2022-02-09 10:06 UTC, normanmaurer commented on codec-http/src/main/java/io/netty/handler/codec/http/TooLongHttpLineException.java
> +public class TooLongHttpLineException extends TooLongFrameException {
```suggestion
public final class TooLongHttpLineException extends TooLongFrameException {
```

2022-02-09 10:06 UTC, normanmaurer commented on codec-http/src/main/java/io/netty/handler/codec/http/TooLongHttpLineException.java
> + * Copyright 2012 The Netty Project
```suggestion
 * Copyright 2022 The Netty Project
```

2022-02-09 10:06 UTC, normanmaurer commented on codec-http/src/main/java/io/netty/handler/codec/http/TooLongHttpContentException.java
> + * Copyright 2012 The Netty Project
```suggestion
 * Copyright 2022 The Netty Project
```

2022-02-09 10:06 UTC, normanmaurer commented on codec-http/src/main/java/io/netty/handler/codec/http/TooLongHttpContentException.java
> +public class TooLongHttpContentException extends TooLongFrameException {
```suggestion
public final class TooLongHttpContentException extends TooLongFrameException {
```

2022-02-09 10:06 UTC, normanmaurer commented on codec-http/src/main/java/io/netty/handler/codec/http/TooLongHttpHeaderException.java
> + * Copyright 2012 The Netty Project
```suggestion
 * Copyright 2022 The Netty Project
```

2022-02-09 10:06 UTC, normanmaurer commented on codec-http/src/main/java/io/netty/handler/codec/http/TooLongHttpHeaderException.java
> +public class TooLongHttpHeaderException extends TooLongFrameException {
```suggestion
public final class TooLongHttpHeaderException extends TooLongFrameException {
```

2022-02-12 08:58 UTC, hyperxpro approved these changes

2022-02-14 14:51 UTC, normanmaurer approved these changes

2022-02-14 14:54 UTC, merged