(Re-) add buffer methods to read/write booleans
netty/netty pull request #12169
Opened 2022-03-12 18:53 UTC by derklaro

Motivation:
The buffer api provides read/write access to all primitive data types except booleans which makes reading and writing them a hassle. This is especially because `writeByte` now takes an actual byte rather than an integer which requires a cast making the write code look (something) like this: `writeByte((byte) (value ? 1 : 0))`. This looks really messy when you need to do this a lot.

Modification:
The `BufferAccessor` now has the same read/write methods (`readBoolean`, `getBoolean(offset)`, `writeBoolean(value)` and `setBoolean(offset, value)`) as all other primitive data types do.

Result:
Writing and reading a boolean from a buffer is now much easier and cleaner than before.

2022-03-14 13:29 UTC, derklaro commented on buffer/src/main/java/io/netty5/buffer/api/BufferAccessor.java
> +    Buffer setBoolean(int woff, boolean value);
Wasn't sure if netty is using default methods as I didn't saw any on the first look :)

2022-03-14 14:58 UTC, derklaro commented
@chrisvest I've added the javadoc comments, hopefully they are as you had them in mind 🤔

2022-03-14 15:35 UTC, chrisvest approved these changes
Yep, that's what I had in mind. I see you already signed the CLA, too. 👍

2022-03-14 15:39 UTC, normanmaurer approved these changes

2022-03-14 15:40 UTC, franz1981 requested changes
LGTM, but consider placing 0 and 1 in appropriate static final int fields

2022-03-15 05:59 UTC, franz1981 commented
@derklaro If we believe the contract will be stable over time (and I suppose is it true) it can be on the interface too, @chrisvest ?

2022-03-15 10:03 UTC, merged