Allow to configure non-built-in socket options
netty/netty pull request #12246
Opened 2022-03-29 09:41 UTC by normanmaurer

Motivation:

More and more socket options are added on every kernel / OS release. While we have "build-in" support for the most used there are situations when the user might want to specify something that we have not build-in.

Modifications:

- Add IntegerUnixChannelOption and RawUnixChannelOption which allows to set socket options that are not "build-in".
- Add unit tests

Result:

More flexibility for the user

2022-03-29 15:44 UTC, chrisvest requested changes

2022-03-29 15:44 UTC, chrisvest commented on transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollSocketTest.java
> +        return 2;
These are the same as their super-class implementations.

2022-03-29 17:45 UTC, normanmaurer commented on transport-native-unix-common/src/main/java/io/netty/channel/unix/Socket.java
> +            throws IOException;
We could do something like that but not for the ChannelOption

2022-03-29 19:05 UTC, chrisvest approved these changes

2022-03-30 08:00 UTC, normanmaurer commented on transport-native-unix-common/src/main/java/io/netty/channel/unix/Socket.java
> +            throws IOException;
fixed

2022-03-30 13:02 UTC, merged