Migrate Compression API to new Buffer API
netty/netty pull request #12426
Opened 2022-05-25 14:19 UTC by normanmaurer

Motivation:

We introduced a new Buffer API in netty 5 but didnt migrate the Compression
to use it yet

Modifications:

- Port Compression API and implementations to use new Buffer API
- Adjust tests

Result:

Use new Buffer API in compression implementations

2022-05-25 14:20 UTC, normanmaurer commented
This also includes https://github.com/netty/netty/pull/12424 which I will remove from this PR once https://github.com/netty/netty/pull/12424 is merged

2022-05-25 22:28 UTC, chrisvest requested changes
Looks good overall. Had a number of small comments.

2022-05-25 22:28 UTC, chrisvest commented on codec/src/test/java/io/netty5/handler/codec/compression/SnappyFrameEncoderTest.java
> +        }); CompositeBuffer actual = CompressionTestUtils.compose(channel.bufferAllocator(), channel::readOutbound)) {
Missing line break?

2022-05-25 22:28 UTC, chrisvest commented on codec/src/test/java/io/netty5/handler/codec/compression/SnappyTest.java
> +        }); Buffer out = BufferAllocator.onHeapUnpooled().allocate(7);
Missing line break?

2022-05-25 22:28 UTC, chrisvest commented on codec/src/test/java/io/netty5/handler/codec/compression/SnappyTest.java
> +        }); Buffer out = BufferAllocator.onHeapUnpooled().allocate(7);
Oh, we're still in the resource expression here. Still looks weird, though.

2022-05-25 22:28 UTC, chrisvest commented on codec/src/test/java/io/netty5/handler/codec/compression/SnappyTest.java
> +        try (Buffer in = BufferAllocator.onHeapUnpooled().copyOf(srcStr.getBytes(StandardCharsets.US_ASCII));
```suggestion
        try (Buffer in = BufferAllocator.onHeapUnpooled().copyOf(srcStr, StandardCharsets.US_ASCII);
```

2022-05-25 22:28 UTC, chrisvest commented on codec/src/test/java/io/netty5/handler/codec/compression/SnappyTest.java
> +                    srcStr.getBytes(StandardCharsets.US_ASCII))) {
```suggestion
            Buffer expectedDecoded = BufferAllocator.onHeapUnpooled().copyOf(
                    srcStr, StandardCharsets.US_ASCII)) {
```

2022-05-25 22:28 UTC, chrisvest commented on codec/src/test/java/io/netty5/handler/codec/compression/SnappyTest.java
> +             Buffer expectedDecompressed = BufferAllocator.onHeapUnpooled().allocate(256)) {
Wonky indentation.

2022-05-25 22:28 UTC, chrisvest commented on codec/src/test/java/io/netty5/handler/codec/compression/ZstdEncoderTest.java
> +            assertTrue(channel.writeOutbound(in2));
`in2` would contain all the remaining readable bytes of `data`, so can't we just pass `data` here?
If so, then we could also inline `in` above, so neither local variable is necessary.

2022-05-25 22:28 UTC, chrisvest commented on codec/src/main/java/io/netty5/handler/codec/compression/ByteBufChecksum.java
> +class ByteBufChecksum implements Checksum {
We could rename this to `BufferChecksum`

2022-05-27 06:24 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/BrotliCompressor.java
> +                byte[] uncompressed = new byte[input.readableBytes()];
future is fine imho

2022-05-27 06:27 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/ZstdCompressor.java
> +        return allocator.allocate((int) bufferSize);
yes and and also if an allocator would be able to allocate direct and heap buffers just like it did in 4.1

2022-05-27 06:27 UTC, normanmaurer commented on codec/src/test/java/io/netty5/handler/codec/compression/AbstractDecoderTest.java
> -            Unpooled.wrappedBuffer(BYTES_LARGE)).asReadOnly();
it doesnt really matter imho

2022-05-27 06:28 UTC, normanmaurer commented on codec/src/test/java/io/netty5/handler/codec/compression/AbstractDecoderTest.java
> +        assertTrue(channel.writeInbound(data.readSplit(data.readableBytes())));
yes as the data is closed automatically later on

2022-05-27 06:28 UTC, normanmaurer commented on codec/src/test/java/io/netty5/handler/codec/compression/AbstractIntegrationTest.java
> +            //closeChannels();
good catch!

2022-05-27 06:29 UTC, normanmaurer commented on codec/src/test/java/io/netty5/handler/codec/compression/CompressionTestUtils.java
> +        }
sure can do this... that said it not really matters for tests imho

2022-05-30 12:09 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/BrotliDecompressor.java
>          return copy;
lets change this.

2022-05-30 12:12 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/FastLzCompressor.java
> +        Buffer out = allocator.allocate(in.readableBytes() / 2);
lets use `/ 1.5`

2022-05-30 12:13 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/Lz4Decompressor.java
> +                                uncompressed = allocator.allocate(decompressedLength);
yeah doesn't make any difference imho. Lets leave it as it is

2022-05-30 12:14 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/LzfDecompressor.java
> +                        if (in.countReadableComponents() == 1) {
good catch..

2022-05-30 12:23 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/LzfDecompressor.java
> +                        if (in.countReadableComponents() == 1) {
fixed

2022-05-30 12:23 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/Snappy.java
> +        out.skipWritable(length);
does it matter ? But sure why not.

2022-05-30 19:07 UTC, normanmaurer commented
Something is wrong with gzip handling ... investigating

2022-05-31 22:30 UTC, chrisvest reviewed
Looking good. Had a couple of more comments.

2022-05-31 22:30 UTC, chrisvest commented on codec-http/src/main/java/io/netty5/handler/codec/http/websocketx/extensions/compression/DeflateEncoder.java
> +                bufferList.add(partCompressedContent.split().send());
Same here. The remainder of `partCompressedContent` is not closed.

2022-05-31 22:30 UTC, chrisvest commented on codec/src/main/java/io/netty5/handler/codec/compression/ZlibCompressor.java
> +                        footer.writeByte((byte) ((crcValue >>> 24)));
Looks like there are some extra parenthesis.

2022-06-01 10:45 UTC, normanmaurer commented on codec-http/src/main/java/io/netty5/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java
> +                bufferList.add(partUncompressedContent.split().send());
@chrisvest let me look into the new method and fix it inline for now

2022-06-01 11:16 UTC, normanmaurer commented on codec/src/main/java/io/netty5/handler/codec/compression/ZlibDecompressor.java
> +        /*
I fixed it.... its a bit more "complicated" then before as ensureWritable(...) not throws if the implicitCapacity is hit. I think it maybe should @chrisvest WDYT ?

2022-06-01 16:10 UTC, chrisvest approved these changes

2022-06-01 22:42 UTC, chrisvest commented
@normanmaurer I'm merging this. We can do cleanups based on #12439 in a separate PR.

2022-06-01 22:43 UTC, merged