Deprecate uninterruptible future methods for removal
netty/netty pull request #12481
Opened 2022-06-16 22:38 UTC by chrisvest

Motivation:
We don't want to directly expose blocking methods on our netty Future interface, because they can't be called inside the event loop.
Instead, users of these should convert the future to a JDK future.
As a step towards this, we should deprecate and remove the uninterruptible blocking methods.
These in particular have no equivalent on the JDK future API.
They are also inherently not behaving properly with regards to interrupts.

Modification:
Deprecate all Future.*Uninterruptible methods for removal.
Replace nearly all usages with interruptible counterparts.

Result:
Fewer suspicious APIs on the Future interface.

2022-06-19 15:54 UTC, normanmaurer commented on common/src/main/java/io/netty5/util/concurrent/Future.java
>      Future<V> syncUninterruptibly();
nit: why not just remove it directly ?

2022-06-19 15:54 UTC, normanmaurer commented on common/src/main/java/io/netty5/util/concurrent/Future.java
>      Future<V> syncUninterruptibly();
Same question for the other methods

2022-06-19 15:57 UTC, normanmaurer requested changes
All in all this looks good but I think we should just remove the methods directly

2022-06-21 18:07 UTC, chrisvest commented
Alright, I'll update the PR to remove them completely.

2022-06-22 22:27 UTC, chrisvest commented
@normanmaurer The methods are now removed.

2022-06-22 23:50 UTC, normanmaurer approved these changes

2022-06-23 00:15 UTC, merged