Peel-off AbstractChannelHandlerContext's ChannelHandlers call-sites
netty/netty pull request #12591
Opened 2022-07-11 05:34 UTC by franz1981

Motivation:
AbstractChannelHandlerContext invoke* methods often fall-off to itable_stub due to interface megamorphism, causing frequent (and mandatory) handlers to not benefit from inlining.

Modification:
Add instanceof checks to peel-off AbstractChannelHandlerContext call-sites for the most frequent (and possibly, mandatory) ChannelHandler's concrete types, to both reduce the arity of the remaining call-site, to improve likelihood of mono/bi-morphism on it, while making possible inlining for the checked ones.

Result:
Faster and more predictable (without itable_stub) ChannelHandlers methods calls propagation.

2022-07-11 05:40 UTC, franz1981 commented
I've collected call-sites type profiling on different Techempower benchmarks using both Vert-x and Quarkus, but I'm sure some of the checks I've performed makes sense for other users/common Netty users (to be defined): please @normanmaurer feel free to suggest different ones otherwise (and/or fix the ones I've found).

Probably Netty 5 requires a similar treatment due to how JIT works (https://shipilev.net/blog/2015/black-magic-method-dispatch/ for more info; ancient but still very good) 

Furthermore: given that we have concrete types built-in on Netty that we care about, we can even decide to enrich the existing list with more, saving any virtual calls and favour inlining (whatever possible) to happen for them.

@njhill did you see this already?

2022-07-11 08:54 UTC, franz1981 commented
@trustin did you noticed anything about it on Armenia as well?  Suggestions are wellcome :D

2022-07-12 05:16 UTC, normanmaurer commented
@franz1981 hmm.. But wouldn't this hurt all the other "handlers" as it will always do the instanceof checks and it will only work for the head and tail ?

2022-07-12 06:00 UTC, franz1981 commented
@normanmaurer 
Right, if we got itable_stub it means that in a callchain  "someone" called a method of the context that didn't got inlined, meaning that use a (shared) compiled version of it, sharing type profiling information of different handlers called into it.
Hitting the itable_stub on some handler method call means that JIT is going to use an optimized dispatch/jump table that still contains these checks (head/tail) because these are types seen with some probability at runtime.
The handle call would just not benefit from being inlined in the context body and the jump table requires jumping in a differente assembly location (that's not super icache friendly).

Thanks to your comment, I see that the real question is on the beginning of this same comment 

> "someone" called a method of the context that didn't got inlined
 
I'll investigate a but more

2022-07-13 11:53 UTC, normanmaurer commented
> @normanmaurer Right, if we got itable_stub it means that in a callchain "someone" called a method of the context that didn't got inlined, meaning that use a (shared) compiled version of it, sharing type profiling information of different handlers called into it. Hitting the itable_stub on some handler method call means that JIT is going to use an optimized dispatch/jump table that still contains these checks (head/tail) because these are types seen with some probability at runtime. The handle call would just not benefit from being inlined in the context body and the jump table requires jumping in a differente assembly location (that's not super icache friendly).
> 
> Thanks to your comment, I see that the real question is on the beginning of this same comment
> 
> > "someone" called a method of the context that didn't got inlined
> 
> Why?
> 
> I'll investigate a bit more, but maybe you got some clue already here: the idea is to make a handler chain event/call to be more JIT friendly

So the question was really if this makes sense at all as sure it helps for the tail and head but imho it might hurt for the rest of the pipeline ass you basically do two instanceof checks that almost always will fail (these will only be true for two handlers).

2022-07-13 12:06 UTC, franz1981 commented
> So the question was really if this makes sense at all as sure it helps for the tail and head but imho it might hurt for the rest of the pipeline ass you basically do two instanceof checks that almost always will fail (these will only be true for two handlers).

This is going to be true only if intermediate contexts fireXXX methods are inlined: if inlined these checked will mostly fail (and the JIT can decide to move it elsewhere given that are "unlikely" to happen

if these methods are not inlined, but compiled, it means that *any* context will share the same fireXXX method with the same call-site type profiling data: it means that the handler call will likely become megamorphic and itable_stub will still perform the check vs head/tail types anyway (because these are seen types as well) but:
- moving into the assembly region that perform the itable_stub call dispatch
- not making the channel handlers (head/tail) calls to benefit from inlining 

In short: if not inlined, these checks will still be performed, but with less optimizations (re inlining and instruction-cache sympathy), if inlined they still be nicely predicted (and correctly placed by the JIT) because almost false for that assembly code

2022-07-14 18:57 UTC, doom369 commented
Can you please share the call sites you mentioned? Also, do you have a benchmark that shows the difference?

2022-07-15 14:24 UTC, franz1981 commented
@normanmaurer @doom369 
> Can you please share the call sites you mentioned?

![image](https://user-images.githubusercontent.com/13125299/179243084-c5123128-1389-4b24-a7d6-231057ce4b4c.png)

> Also, do you have a benchmark that shows the difference?

Still WIP, same for compilation logs (the perf issue is low prio ATM), but the whole channel pipeline here doesn't have lot of handlers defined; it's a normal HTTP 1.1 pipeline :)

2022-07-18 12:32 UTC, normanmaurer requested changes

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                    ((DefaultChannelPipeline.TailContext) handler).userEventTriggered(null, event);
```suggestion
                    ((DefaultChannelPipeline.TailContext) handler).userEventTriggered(this, event);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                    ((DefaultChannelPipeline.TailContext) handler).channelInactive(null);
```suggestion
                    ((DefaultChannelPipeline.TailContext) handler).channelInactive(this);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                    ((DefaultChannelPipeline.TailContext) handler).channelRegistered(null);
```suggestion
                    ((DefaultChannelPipeline.TailContext) handler).channelRegistered(this);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                    ((DefaultChannelPipeline.TailContext) handler).channelUnregistered(null);
```suggestion
                    ((DefaultChannelPipeline.TailContext) handler).channelUnregistered(this);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                    ((DefaultChannelPipeline.TailContext) handler).channelActive(null);
```suggestion
                    ((DefaultChannelPipeline.TailContext) handler).channelActive(this);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                    ((DefaultChannelPipeline.TailContext) handler).channelReadComplete(null);
```suggestion
                    ((DefaultChannelPipeline.TailContext) handler).channelReadComplete(this);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                    ((DefaultChannelPipeline.TailContext) handler).channelWritabilityChanged(null);
```suggestion
                    ((DefaultChannelPipeline.TailContext) handler).channelWritabilityChanged(this);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                ((DefaultChannelPipeline.HeadContext) handler).write(null, msg, promise);
```suggestion
                ((DefaultChannelPipeline.HeadContext) handler).write(this, msg, promise);
```

2022-07-18 12:32 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
> +                ((DefaultChannelPipeline.HeadContext) handler).flush(null);
```suggestion
                ((DefaultChannelPipeline.HeadContext) handler).flush(this);
```

2022-07-21 09:00 UTC, franz1981 commented
@doom369 did you get similar figures in prod envs?

2022-07-28 14:27 UTC, doom369 commented
@franz1981 yes. I have seen that. However, the last time I did profiling - it was a JVM 11, 1 year ago, now we're on JVM 17 (and there were many changes since). What JVM version did you test against?

2022-08-10 10:55 UTC, franz1981 commented
@doom369 Recently having fun with how JDK treat megamorphism and inline caches and I can tell we won't get that much benefit by new versions on that (the version I've tested was both jdk 11 and the very latest LTS)

2022-08-10 15:52 UTC, chrisvest commented
If the latest JITs can derive the same or similar optimisation from cleaner code, then I'm partial to having cleaner code and let people on older JVMs have marginally worse performance.

2022-08-21 21:47 UTC, franz1981 commented
Sorry @chrisvest catching up, I see my comment wasn't clear on

> I can tell we won't get that much benefit by new versions on that (the version I've tested was both jdk 11 and the very latest LTS)

I mean that new JDK version aren't still able to improve things here: we need a different approach, although I see that would make the code worse - let me try in our perf rig what kind of improvement I can get.
On JMH too

2022-09-15 14:18 UTC, closed without merging