Add WriteHandleFactory which allows more control over the write loop.
netty/netty pull request #12702
Opened 2022-08-16 09:13 UTC by normanmaurer

Motivation:

We already provide some means of influence the read loop by ReadHandleFactory but we didnt offer the same for the write loop.

Modifications:

- Add WriteHandleFactory which allows to influence the write loop.
- Remove ChannelOption.MAX_MESSAGES_PER_WRITE as this should be done as a WriteHandleFactory implentation.
- Move logic for sizing the maximum bytes per gather write to SocketWriteHandleFactory and re-use it by different SocketChannel implementations

Result:

Much more control for the end-user and more code-sharing

2022-08-16 18:03 UTC, chrisvest requested changes

2022-08-17 06:39 UTC, normanmaurer commented on transport/src/main/java/io/netty5/channel/socket/nio/NioDatagramChannel.java
> +                    writtenBytes = write(copy, remoteAddress);
I am not sure the looping was the correct thing ... as generally speaking we change the semantics (make multiple datagrams out of one).

2022-08-17 07:09 UTC, normanmaurer commented on transport-native-kqueue/src/test/java/io/netty5/channel/kqueue/KQueueCompositeBufferGatheringWriteTest.java
> +            //((AbstractKQueueChannel<?>) channel).setMaxBytesPerGatheringWrite(soSndBuf);
fixed

2022-08-17 07:33 UTC, normanmaurer commented on transport-classes-kqueue/src/main/java/io/netty5/channel/kqueue/KQueueSocketChannel.java
> +            writtenMessages = cnt;
fixed

2022-08-17 09:39 UTC, normanmaurer commented on transport-classes-kqueue/src/main/java/io/netty5/channel/kqueue/KQueueDatagramChannel.java
> +                in.remove();
nope just a left-over

2022-08-17 15:42 UTC, chrisvest approved these changes

2022-08-17 15:43 UTC, merged