Speed up HTTP/2 header iteration
netty/netty pull request #12843
Opened 2022-09-27 22:57 UTC by chrisvest

Motivation:
When iterating HTTP/2 headers, the pseudo-headers must always come first in iteration order.
We previously solved this by iterating the headers twice, filtering, and concatenating the two filtered iterations.
This was very slow, but meant we could use the MultiMap pretty much unchanged.

Modification:
Add another pair of linkage references to the entries in the MultiMap.
This doubly-linked list preserves total insertion order, except pseudo-headers are always arranged before normal headers.
We use a handful of fields to keep track of where pseudo-headers start and end, and likewise for normal headers.
For iteration we then use this new chain instead of the bucket-head and entries chains.

Result:
Iteration of HTTP/2 headers is now over 700% faster, but 'add' and 'addAll' methods are slower by 22-44%, when benchmarked with 30 headers.

2022-09-27 22:59 UTC, chrisvest commented
Visualization of the benchmark results:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/7993/192652200-74a632f6-cf53-4830-a636-ff560231c1c1.png">

2022-09-28 01:48 UTC, Scottmitch approved these changes
approach lgtm, good work @chrisvest! note I didn't look closely at the linking details but I assume you have this covered with tests.

2022-09-28 03:06 UTC, normanmaurer requested changes
two small things... Great work!

2022-09-28 03:06 UTC, normanmaurer commented on codec-http2/src/main/java/io/netty5/handler/codec/http2/headers/DefaultHttp2Headers.java
> +    private static class Http2MultiMapEntry extends MultiMapEntry<CharSequence, CharSequence> {
```suggestion
    private static final class Http2MultiMapEntry extends MultiMapEntry<CharSequence, CharSequence> {
```

2022-09-28 03:06 UTC, normanmaurer commented on codec-http2/src/main/java/io/netty5/handler/codec/http2/headers/DefaultHttp2Headers.java
> +    private class FullHttp2EntryIterator implements Iterator<Entry<CharSequence, CharSequence>> {
```suggestion
    private final class FullHttp2EntryIterator implements Iterator<Entry<CharSequence, CharSequence>> {
```

2022-09-29 19:49 UTC, merged