Fix scalability issue of ByteToMessageDecoder sub-classes that also i…
netty/netty pull request #12891
Opened 2022-10-13 08:38 UTC by normanmaurer

…mplement ChannelOutboundHandler

Motivation:

There is some scalability issue with ChannelHandler implementations that implement ChannelInboundHandler and ChannelOutboundHandler at the same time. This can be fixed by usually extending ChannelDuplexHandler. Unfortunally this is not possible when the ChannelHandler in question already extend ByteToMessageDecoder, which is the case for SslHandler which is a very popular handler. To fix this let's just have ByteToMessageDecoder extend ChannelDuplexHandler. This will not hurt in general as we will still skip execution of the outbound methods if te sub-class is not overriding these while also ensure that we not get into trouble of scalability issues.

Modifications:

Let ByteToMessageDecoder extend ChannelDuplexHandler

Result:

Workaround scalability issue of SslHandler.

2022-10-13 08:38 UTC, normanmaurer commented
This really makes me cry ... But I think there is nothing else we can do atm :/ 

/cc @franz1981 @chrisvest

2022-10-13 11:56 UTC, franz1981 commented
> This really makes me cry

I know @normanmaurer what you mean :( 


My suggestion is to compile with JDK 11 and run one of the examples attaching https://github.com/franz1981/type-pollution-agent and see what it reports.
Maybe the outbound methods used aren't hot/frequently taken (as `IdleStateHandler` or `HeadContext` that requires to capture *everything* ) and we don't need to address it like this (although I admit is the nearly one liner change that fix everything)

eg 
```
    void read(ChannelHandlerContext ctx) throws Exception;
    void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception;
    void flush(ChannelHandlerContext ctx) throws Exception;
```
the methods above are supposed to be hot-paths ones, but if who implements `ChannelOutboundHandler` is skipping them, it shouldn't be a problem (thinking about some that just need to capture `close`....)

2022-10-13 11:57 UTC, franz1981 approved these changes
LGTM

`SslHandler` is indeed very used :"(

2022-10-13 19:58 UTC, chrisvest requested changes
The `SslHandler` no longer needs to explicitly implement `ChannelOutboundHandler`.

Revapi is not happy, but I don't _think_ it'll be an issue in practice. So we'll need to add some new ignores. The pom.xml file already has examples of what this looks like.

2022-10-14 09:32 UTC, normanmaurer commented
@chrisvest I left the `implements` just in case someone has some mix up with netty versions between `codec` and `handler` . I also think it shouldn't be a problem in real-world. But I think we might want to do some benchmarking first to ensure we really need this.

2022-10-14 22:56 UTC, chrisvest commented
It's now getting test failures and leaks, e.g.

```
2022-10-14T13:45:56.1992875Z [ERROR] testHttpResponseAndFrameInSameBufferCodec  Time elapsed: 0.01 s  <<< ERROR!
2022-10-14T13:45:56.1993543Z java.lang.IllegalArgumentException: inboundHandler must not implement ChannelOutboundHandler to get combined.
2022-10-14T13:45:56.1994276Z 	at io.netty.channel.CombinedChannelDuplexHandler.validate(CombinedChannelDuplexHandler.java:88)
2022-10-14T13:45:56.1995107Z 	at io.netty.channel.CombinedChannelDuplexHandler.init(CombinedChannelDuplexHandler.java:70)
2022-10-14T13:45:56.1995797Z 	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:108)
2022-10-14T13:45:56.1996434Z 	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:98)
2022-10-14T13:45:56.1997069Z 	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:89)
2022-10-14T13:45:56.1997692Z 	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:73)
2022-10-14T13:45:56.1998655Z 	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBuffer(WebSocketClientHandshakerTest.java:348)
2022-10-14T13:45:56.1999939Z 	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBufferCodec(WebSocketClientHandshakerTest.java:283)
```

```
2022-10-14T13:46:01.9979069Z [INFO] Results:
2022-10-14T13:46:01.9985430Z [INFO] 
2022-10-14T13:46:01.9991780Z [ERROR] Failures: 
2022-10-14T13:46:01.9998308Z [ERROR]   HttpClientCodecTest.testServerCloseSocketInputProvidesData:199 expected: <true> but was: <false>
2022-10-14T13:46:02.0010707Z [ERROR] Errors: 
2022-10-14T13:46:02.0035702Z [ERROR]   HttpClientCodecTest.testConnectWithResponseContent:69 » IllegalArgument inboun...
2022-10-14T13:46:02.0036585Z [ERROR]   HttpClientCodecTest.testContinueParsingAfterConnect:213->testAfterConnect:222 » IllegalArgument
2022-10-14T13:46:02.0037497Z [ERROR]   HttpClientCodecTest.testDecodesFinalResponseAfterSwitchingProtocols:294 » IllegalArgument
2022-10-14T13:46:02.0038369Z [ERROR]   HttpClientCodecTest.testFailsNotOnRequestResponseChunked:78 » IllegalArgument ...
2022-10-14T13:46:02.0039182Z [ERROR]   HttpClientCodecTest.testFailsOnIncompleteChunkedResponse:105 » IllegalArgument
2022-10-14T13:46:02.0039977Z [ERROR]   HttpClientCodecTest.testFailsOnMissingResponse:87 » IllegalArgument inboundHan...
2022-10-14T13:46:02.0040792Z [ERROR]   HttpClientCodecTest.testInformationalResponseKeepsPairsInSync:371 » IllegalArgument
2022-10-14T13:46:02.0041814Z [ERROR]   HttpClientCodecTest.testMultipleResponses:409 » IllegalArgument inboundHandler...
2022-10-14T13:46:02.0042619Z [ERROR]   HttpClientCodecTest.testPassThroughAfterConnect:218->testAfterConnect:222 » IllegalArgument
2022-10-14T13:46:02.0043394Z [ERROR]   HttpClientCodecTest.testWebDavResponse:348 » IllegalArgument inboundHandler mu...
2022-10-14T13:46:02.0044147Z [ERROR]   HttpClientCodecTest.testWebSocket00Response:327 » IllegalArgument inboundHandl...
2022-10-14T13:46:02.0044921Z [ERROR]   HttpClientCodecTest.testWriteThroughAfterUpgrade:429 » IllegalArgument inbound...
2022-10-14T13:46:02.0045743Z [ERROR]   HttpContentCompressorTest.testExecutorPreserveOrdering » StacklessClosedChannel
2022-10-14T13:46:02.0046523Z [ERROR]   HttpServerCodecTest.test100Continue:74 » IllegalArgument inboundHandler must n...
2022-10-14T13:46:02.0047290Z [ERROR]   HttpServerCodecTest.testChunkedHeadFullHttpResponse:154 » IllegalArgument inbo...
2022-10-14T13:46:02.0048086Z [ERROR]   HttpServerCodecTest.testChunkedHeadResponse:123 » IllegalArgument inboundHandl...
2022-10-14T13:46:02.0048901Z [ERROR]   HttpServerCodecTest.testUnfinishedChunkedHttpRequestIsLastFlag:40 » IllegalArgument
2022-10-14T13:46:02.0049722Z [ERROR]   HttpServerUpgradeHandlerTest.skippedUpgrade:152 » IllegalArgument inboundHandl...
2022-10-14T13:46:02.0050504Z [ERROR]   HttpServerUpgradeHandlerTest.upgradeFail:196 » IllegalArgument inboundHandler ...
2022-10-14T13:46:02.0051368Z [ERROR]   HttpServerUpgradeHandlerTest.upgradesPipelineInSameMethodInvocation:71 » IllegalArgument
2022-10-14T13:46:02.0052689Z [ERROR]   WebSocketClientHandshaker00Test>WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBufferCodec:283->WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBuffer:348 » IllegalArgument
2022-10-14T13:46:02.0054261Z [ERROR]   WebSocketClientHandshaker07Test>WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBufferCodec:283->WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBuffer:348 » IllegalArgument
2022-10-14T13:46:02.0055824Z [ERROR]   WebSocketClientHandshaker08Test>WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBufferCodec:283->WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBuffer:348 » IllegalArgument
2022-10-14T13:46:02.0061593Z [ERROR]   WebSocketClientHandshaker13Test>WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBufferCodec:283->WebSocketClientHandshakerTest.testHttpResponseAndFrameInSameBuffer:348 » IllegalArgument
2022-10-14T13:46:02.0063037Z [ERROR]   WebSocketHandshakeHandOverTest.testClientHandshakeTimeout:136->createServerChannel:358->createServerChannel:365 » IllegalArgument
2022-10-14T13:46:02.0064036Z [ERROR]   WebSocketHandshakeHandOverTest.testClientHandshakerForceClose:240->createServerChannel:365 » IllegalArgument
2022-10-14T13:46:02.0064984Z [ERROR]   WebSocketHandshakeHandOverTest.testHandover:89->createServerChannel:358->createServerChannel:365 » IllegalArgument
2022-10-14T13:46:02.0066069Z [ERROR]   WebSocketHandshakeHandOverTest.testHandshakeFutureIsNotifiedOnChannelClose:205->createClientChannel:325->createClientChannel:340 » IllegalArgument
2022-10-14T13:46:02.0067047Z [ERROR]   WebSocketServerHandshaker13Test.testCloseReasonWithCodec:95 » IllegalArgument ...
2022-10-14T13:46:02.0068077Z [ERROR]   WebSocketServerProtocolHandlerTest.testCloseFrameSentWhenClientChannelClosedSilently:381->createClient:409 » IllegalArgument
2022-10-14T13:46:02.0069769Z [ERROR]   WebSocketServerProtocolHandlerTest.testCloseFrameSentWhenServerChannelClosedSilently:330->createClient:409 » IllegalArgument
2022-10-14T13:46:02.0071002Z [ERROR]   WebSocketServerProtocolHandlerTest.testExplicitCloseFrameSentWhenClientChannelClosed:356->createClient:409 » IllegalArgument
2022-10-14T13:46:02.0072174Z [ERROR]   WebSocketServerProtocolHandlerTest.testExplicitCloseFrameSentWhenServerChannelClosed:304->createClient:409 » IllegalArgument
2022-10-14T13:46:02.0072866Z [INFO] 
2022-10-14T13:46:02.0073389Z [ERROR] Tests run: 2311, Failures: 1, Errors: 33, Skipped: 2
```

2022-10-17 13:49 UTC, normanmaurer commented
Oh well... I didn't think about this. So its not possible

2022-10-17 13:49 UTC, closed without merging