Fix generating the `Origin` header value for websocket handshake request
netty/netty pull request #12941
Opened 2022-10-31 11:23 UTC by amizurov

Motivation:

We have the old erroneous behavior of generating the `Origin| Sec-WebSocket-Origin` for client websocket handshake request (https://github.com/netty/netty/issues/9673). In Netty5 this fixed and auto-generation has beed deleted at all, only if the client passed the `Origin` header via custom headers. The same we can do for Netty4 but it could potentially break some clients (unlikely), or introduce an additional parameter to disable or enable this behavior.

Modification:

Introduce new `enableGenerateOriginHeader` parameter in client config and generate the `Origin|Sec-WebSocket-Origin` header value only if it enabled.

Result:

Fixes https://github.com/netty/netty/issues/9673 https://github.com/netty/netty/issues/12933

2022-10-31 11:25 UTC, amizurov commented
@normanmaurer , @chrisvest @vietj , @slandelle Could you please take a look.

2022-10-31 18:43 UTC, chrisvest commented
One fixes the NPE by turning origin header generation off?

2022-10-31 22:57 UTC, ursaj commented
looks good

2022-11-01 09:20 UTC, amizurov commented
> One fixes the NPE by turning origin header generation off?

Added a comment to the issue https://github.com/netty/netty/issues/12933 how they are related.

2022-11-02 16:40 UTC, chrisvest approved these changes

2022-11-03 15:41 UTC, amizurov commented
@normanmaurer @vietj @slandelle Could you please review this changes, i would like to know your thoughts.

2022-11-10 10:22 UTC, normanmaurer requested changes
Just some comments related to the test-code. PTAL

2022-11-10 10:22 UTC, normanmaurer commented on codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakerTest.java
> +        });
This is an odd usage of assertThrows:

```suggestion
        assertInstanceOf(IllegalArgumentException.class,  handshakeFuture.cause());
```

2022-11-10 10:22 UTC, normanmaurer commented on codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakerTest.java
> +        });
This is an odd usage of assertThrows:

```suggestion
        assertInstanceOf(IllegalArgumentException.class,  handshakeFuture.cause());
```
```

2022-11-10 10:58 UTC, amizurov commented on codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakerTest.java
> +        });
Done

2022-11-10 10:58 UTC, amizurov commented on codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakerTest.java
> +        });
Done

2022-11-10 11:28 UTC, merged

2022-11-10 11:28 UTC, normanmaurer commented
@amizurov thanks a lot!

2022-11-10 17:58 UTC, slandelle reviewed
LGTM. I'm fine with fixing a broken behavior at the cost of a breaking change.