Avoid long stacktrace when netty-resolver-dns-native-macos native library is missing
netty/netty pull request #12950
Opened 2022-11-01 13:06 UTC by violetagg

Motivation:
When `netty-resolver-dns-native-macos` java classes are on the classpath but the native library is missing, the long stacktrace below is printed in the logs. In the log message it is already recommended that a missing dependency may cause the issue, adding this dependency in most cases should fix the issue. This change proposes changes in the information that is provided for this issue depending on the log level:
- When on DEBUG log level the recommendation for checking the dependency and the full stacktrace can be seen
- Otherwise the recommendation for checking the dependency and the cause message can be seen

```
[Test worker] ERROR i.n.r.d.DnsServerAddressStreamProviders - Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:64)
        ...
Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.ensureAvailability(MacOSDnsServerAddressStreamProvider.java:110)
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.<init>(MacOSDnsServerAddressStreamProvider.java:120)
	...
Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_resolver_dns_native_macos_x86_64
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.loadNativeLibrary(MacOSDnsServerAddressStreamProvider.java:92)
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.<clinit>(MacOSDnsServerAddressStreamProvider.java:77)
	...
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_resolver_dns_native_macos
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.loadNativeLibrary(MacOSDnsServerAddressStreamProvider.java:95)
		...
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_resolver_dns_native_macos.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
		...
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			...
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
				at java.lang.Runtime.loadLibrary0(Runtime.java:871)
				at java.lang.System.loadLibrary(System.java:1122)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				...
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_resolver_dns_native_macos_x86_64.jnilib
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
	...
	Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos_x86_64 in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
		at java.lang.Runtime.loadLibrary0(Runtime.java:871)
		at java.lang.System.loadLibrary(System.java:1122)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		...
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			...
```

Modification:
- When `DnsServerAddressStreamProviders` tries to load `MacOSDnsServerAddressStreamProvider` but the needed native library is not available:
  - If the log level is DEBUG log level,  a recommendation for checking the dependency and the full stacktrace can be seen
  - Otherwise, a recommendation for checking the dependency and only the cause message can be seen

Result:
The log file is less verbose when on log level different than DEBUG, but when on DEBUG level, the full information will be available

2022-11-01 18:19 UTC, chrisvest requested changes
The change to the messages are good, but it has a weird effect on the log levels:

If debug logging is enabled, then no ERROR-level messages are printed.
Many people have monitoring alerts for WARN and ERROR level messages, so we should still produce one for that level.

I suggest we keep logging at error level, and only use the isDebugEnabled to change the message.

2022-11-01 18:47 UTC, violetagg commented on resolver-dns/src/main/java/io/netty/resolver/dns/DnsServerAddressStreamProviders.java
> +                    LOGGER.debug("Unable to load {}, fallback to system defaults. This may result in "
```suggestion
                    LOGGER.error("Unable to load {}, fallback to system defaults. This may result in "
```

2022-11-01 18:48 UTC, violetagg commented
@chrisvest PTAL

2022-11-01 19:16 UTC, chrisvest approved these changes

2022-11-02 03:03 UTC, merged

2022-11-02 03:04 UTC, chrisvest commented
Thanks!