Make all native transport tests run parallel-per-class
netty/netty pull request #12997
Opened 2022-11-15 00:50 UTC by chrisvest

Motivation:
Native transport tests were running with a mix of parallel modes. The epoll tests were running fully concurrently, but it looks like the tests cannot tolerate this. The io_uring tests now also run in parallel, as do the kqueue tests.

Modification:
Move the junit configuration to transport-native-common-tests. Make the junit config for the native transports run the tests in parallel class-wise. In other words, within a class the tests will run one at a time in the same thread, but multiple classes can run in parallel.

Result:
Epoll tests should be more stable now (something related to ssl did not like the tests to run fully concurrently).

2022-11-15 01:19 UTC, chrisvest commented
This doesn't solve the real problem; just makes it less likely to bite any given PR. We still see these tests fail for the NIO transport, which isn't running anything in parallel.

2022-11-15 07:46 UTC, normanmaurer requested changes

2022-11-15 07:46 UTC, normanmaurer commented on testsuite/src/main/java/io/netty5/testsuite/transport/socket/SocketTestPermutation.java
> +        public static final File DIR;
```suggestion
        private static final int MAX_PATH_LEN = 128;
        private static final AtomicInteger COUNTER = new AtomicInteger();
        private static final File DIR;
```

2022-11-15 07:46 UTC, normanmaurer commented on testsuite/src/main/java/io/netty5/testsuite/transport/socket/SocketTestPermutation.java
> +                } while (file.toString().length() > maxLen);
Let's ensure we not loop forever
```suggestion
                int maxTries = 64;
                do {
                    if (maxTries-- == 0) {
                        throw new ExceptionInInitializerError("Unable to create temporary file with path length <= " + maxLen);
                    }
                    if (file != null && !file.delete()) {
                        throw new IOException("failed to delete: " + file);
                    }
                    file = PlatformDependent.createTempDirectory("NETTY-UDS", null).getAbsoluteFile();
                } while (file.toString().length() > maxLen);
```

2022-11-18 18:38 UTC, chrisvest commented
@gradinac The Java 17 Graal build found something interesting that looks very much like a Graal JIT compiler bug around VarHandles and x86_64 atomics. I'm guessing you know who to tell about this.

The stack trace of interest looks like this:

```
Caused by: java.lang.IllegalStateException: This object has already been received.
	at io.netty5.buffer.internal.SendFromOwned.gateReception(SendFromOwned.java:54)
	at io.netty5.buffer.internal.SendFromOwned.receive(SendFromOwned.java:46)
	at io.netty5.buffer.BufferInputStream.<init>(BufferInputStream.java:61)
	at io.netty5.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1247)
	at io.netty5.handler.ssl.SslContext.toX509Certificates(SslContext.java:1232)
	at io.netty5.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:378)
	... 110 more
```

The exception comes when `gateReception` fails to flip a volatile boolean field from `false` to `true`, via `getAndSet` through a `VarHandle`: https://github.com/netty/netty/blob/45ead82fba89238a703ce1afca1730dc64a246f1/buffer/src/main/java/io/netty5/buffer/internal/SendFromOwned.java#L52-L61

The field is local to the `SendFromOwned` object, and keeps its initial `false` value until the object is received or closed: https://github.com/netty/netty/blob/45ead82fba89238a703ce1afca1730dc64a246f1/buffer/src/main/java/io/netty5/buffer/internal/SendFromOwned.java#L34

So the happy-path is that the `getAndSet` will return `false`, and atomically set the field value to `true`, preventing any further receives in a thread-safe way. A `Send` can only be received once.

The thing is, the `Buffer`, the `SendFromOwned`, the `send()` and `receive()` calls all happen in the same thread, and all objects are local to that thread.

The buffers are allocated in the `PemReader.readCertificates()` call: https://github.com/netty/netty/blob/main/handler/src/main/java/io/netty5/handler/ssl/SslContext.java#L1228-L1233

Then sent to the `BufferInputStream` constructor purely as a matter of buffer ownership transfer: https://github.com/netty/netty/blob/main/handler/src/main/java/io/netty5/handler/ssl/SslContext.java#L1242-L1255

And received in the constructor, in the same thread: https://github.com/netty/netty/blob/45ead82fba89238a703ce1afca1730dc64a246f1/buffer/src/main/java/io/netty5/buffer/BufferInputStream.java#L60-L66

The `SendFromOwned` object was created by the `send()` call in the `getCertificatesFromBuffers()` call above. The `send()` is implemented like this: https://github.com/netty/netty/blob/45ead82fba89238a703ce1afca1730dc64a246f1/buffer/src/main/java/io/netty5/buffer/internal/ResourceSupport.java#L136-L150

As you can see, each `send()` call creates a new `SendFromOwned` object. The buffer is also put in a state that prevents more `Send` objects from being created, though that's not relevant to this issue.

At no point do any of these objects get shared with other threads, and each buffer is only sent once, and each `Send` is immediately received on the same thread. So there's no way the `received` could be anything other than `false`, yet the `getAndSet` call returns `true` and the exception is thrown.

2022-11-21 10:20 UTC, normanmaurer approved these changes

2022-11-21 10:20 UTC, merged

2022-11-21 12:37 UTC, gradinac commented
@chrisvest Thank you very much for looking into this! :) I've also looked into the gate logs to verify, but just to double check, this happens in the Graal JIT mode, not on native-image?

Could you, if you have the time, open an issue under [oracle/graal](https://github.com/oracle/graal): https://github.com/oracle/graal/issues/new?assignees=&labels=bug&template=5_issues_other.md&title=
One thing that would really help to debug it would be a standalone reproducer. It would be perfect if we had one, but if that's not possible, the set of commands that would run just the above test should also help. I assume it would be something like:

To setup:
```bash
export JAVA_HOME=<path-to-graalvm>
git clone https://github.com/netty/netty.git
cd netty
git fetch origin main
git checkout main
mvn -DskipTests=true install
cd handler
```
To run just this test:
```bash
mvn -Dtest=ParameterizedSslHandlerTest.testCompositeBufSizeEstimationGuaranteesSynchronousWrite test
```

2022-11-28 23:21 UTC, chrisvest commented
@gradinac 
> Could you, if you have the time, open an issue under

Employer says I'm not allowed, so no 🤷 

Reproducer instructions looks correct, except the command to run the test needs to look like this:

```
mvn -Dtest=ParameterizedSslHandlerTest#testCompositeBufSizeEstimationGuaranteesSynchronousWrite test -pl handler
```