Add `ConcurrencyLimit` and its default implementation
netty/netty pull request #13014
Opened 2022-11-21 14:45 UTC by trustin

Motivation:

As a preparatory step for resolving #12842, we need a construct that limits concurrency asynchronously.

Modifications:

- Add `ConcurrencyLimit` and `ConcurrencyLimitHandler`
- Add the default implementation `SimpleConcurrencyLimit`

Result:

- In our future work, we can allow a user to specify a `ConcurrencyLimit` when building a `DnsNameResolver` and use it for limiting the concurrency of DNS queries in `DnsQueryContext.writeQuery()`

2022-11-21 14:46 UTC, normanmaurer commented
@trustin welcome back buddy :)

2022-11-21 16:12 UTC, franz1981 requested changes
I would allow using different queues types for pendingHandlers and would save the PendingHandler in a local variable outside of the CAS loop to reuse it in case of failing CAS.

Furthermore, not a blocker for this, I would implement a more constrained version (with lighter concurrent ops) for single threaded usage too (where it makes sense, to be used always by the same event loop)

2022-11-21 17:07 UTC, hyperxpro commented on common/src/test/java/io/netty/util/concurrent/SimpleConcurrencyLimitTest.java
> +                    events.add("acquired");
I think it'd be good if we declare class-level variables for event names.

2022-11-30 19:32 UTC, chrisvest reviewed
Some comments

2022-11-30 19:32 UTC, chrisvest commented on common/src/main/java/io/netty/util/concurrent/ConcurrencyLimitHandler.java
> +    void permitAcquired(Runnable releaser);
What's the idea behind relying on the callee to invoke the releaser, vs. automatically releasing a permit upon the completion of this method?

2022-11-30 19:32 UTC, chrisvest commented on common/src/main/java/io/netty/util/concurrent/SimpleConcurrencyLimit.java
> +                return;
We have a data-race here where all permits could have been returned, and all releasers could have been called, before we manage to add our pending handler to the queue.

2022-11-30 19:32 UTC, chrisvest commented on common/src/main/java/io/netty/util/concurrent/SimpleConcurrencyLimit.java
> +                return;
Same data-race exists here, with a smaller window.

2022-11-30 19:32 UTC, chrisvest commented on common/src/main/java/io/netty/util/concurrent/SimpleConcurrencyLimit.java
> +                    final PendingHandler pendingHandler = pendingHandlers.poll();
If the pending handler is non-null, we could in theory "hand over" our existing permit, and skip the decrement/increment dance.

2022-12-19 15:44 UTC, trustin commented
I renamed `ConcurrencyLimit` to `Limiter` and `SimpleConcurrencyLimiter` to `ConcurrencyLimiter`, and then added `RateLimiter`. I didn't address the comments yet and there are still some rough edges in the implementation, so I converted this PR to draft. I'll ping you once it's ready for reviews.

2023-01-29 14:43 UTC, trustin commented
Had a chat with @normanmaurer a few days ago and we concluded that at the moment we don't really need any pluggability for rate-limiting DNS queries - just simple rate limiting implemented directly in our resolver implementation will do. Once we find similar use cases in other places in Netty, we may resurrect this PR, but for now, let me close it.

2023-01-29 14:43 UTC, closed without merging