Support handshake timeout in SniHandler.
netty/netty pull request #13041
Opened 2022-12-09 10:52 UTC by vietj

The SslHandler has a configurable timeout that is triggered when the handshake is not completed within that limit. The SniHandler should also have a similar timeout, such timeout would be fired when the the client has not sent enough data to trigger the SNI completion and propagated to the SslHandler it creates.

Added a handshake timeout in the SniHandler that creates a timer task to fire a failed sni completion event, as well as setting the handshake timeout on the SslHandler when it creates it.

Consequently, SniHandler supports handshake timeouts.

2022-12-09 14:20 UTC, vietj commented
not sure what failed in the verify-pr task, if somebody can enlighten me, perhaps I could fix it, but it seems non sense to me.

2022-12-12 08:00 UTC, normanmaurer commented
@vietj I think I fixed it... lets see how the build goes.

2022-12-12 08:09 UTC, normanmaurer requested changes

2022-12-12 08:09 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java
> +    public AbstractSniHandler(long handshakeTimeoutMillis) {
```suggestion
    protected AbstractSniHandler(long handshakeTimeoutMillis) {
```

2022-12-12 08:09 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java
> +    public AbstractSniHandler() {
```suggestion
    protected AbstractSniHandler() {
```

2022-12-12 08:09 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java
> +        checkStartTimeout(ctx);
```suggestion
        ctx.fireChannelActive();
        checkStartTimeout(ctx);
```

2022-12-12 08:09 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java
> +    protected void checkStartTimeout(final ChannelHandlerContext ctx) {
Any reasons why this is protected ?
```suggestion
    private void checkStartTimeout(final ChannelHandlerContext ctx) {
```

2022-12-12 18:42 UTC, vietj commented on handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java
> +    protected void checkStartTimeout(final ChannelHandlerContext ctx) {
nope

2022-12-12 18:43 UTC, vietj commented
All proposed changes look fine to me, if you can just apply them at once it works for me

2022-12-13 08:26 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java
> +    protected AbstractSniHandler() {
```suggestion
    public AbstractSniHandler() {
```

2022-12-19 07:48 UTC, normanmaurer approved these changes

2022-12-19 14:12 UTC, merged