Update: Add snappy support on HttpContentDecoder
netty/netty pull request #13312
Opened 2023-03-30 19:36 UTC by redcinelli

Motivation:
I want to allow logstash http input to be able to read snappy compressed data.

Modifications:
To allow the HttpContentDecoder to support snappy it created a new control flow to test for snappy content encoding.

If it is present, we are using a specific snappy decompressor to read the data.

In order to make sure it was working I also included a e2e test on the behaior of HttpContentDecoder.

Result:
We should be able to send snappy traffic to a server using HttpContentDocder and be ale to uncompresse the traffic.

Fixes #13307

2023-04-02 06:28 UTC, hyperxpro requested changes
Fix checkstyle.

2023-04-02 06:28 UTC, hyperxpro commented on codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecompressor.java
> +        if (SNAPPY.contentEqualsIgnoreCase(contentEncoding)){
```suggestion
        if (SNAPPY.contentEqualsIgnoreCase(contentEncoding)) {
```

2023-04-02 06:28 UTC, hyperxpro commented on codec-http/src/main/java/io/netty/handler/codec/http/HttpHeaderValues.java
> +
```suggestion
 
```

2023-04-02 06:28 UTC, hyperxpro commented on codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java
> +            -22,104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100
```suggestion
            -22, 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100
```

2023-04-02 06:28 UTC, hyperxpro commented on codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java
> +
```suggestion
```

2023-04-02 06:28 UTC, hyperxpro commented on codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java
> +
```suggestion
```

2023-04-02 19:03 UTC, normanmaurer commented on codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecompressor.java
> +            return  new EmbeddedChannel(ctx.channel().id(), ctx.channel().metadata().hasDisconnect(),
```suggestion
            return new EmbeddedChannel(ctx.channel().id(), ctx.channel().metadata().hasDisconnect(),
```

2023-04-03 07:03 UTC, normanmaurer commented
@redcinelli can you please sign our ICLA: https://netty.io/s/icla ?

2023-04-03 07:05 UTC, hyperxpro commented
We also need this for Http2.

2023-04-03 07:22 UTC, redcinelli commented
> @redcinelli can you please sign our ICLA: https://netty.io/s/icla ?

Hi @normanmaurer, I believe I had done it already.
Do I get a confirmation by email ?

I have re-done it anyway just to make sure. 👌

2023-04-03 09:59 UTC, merged