Pseudo-header with empty value results in RST_STREAM with PROTOCOL_ERROR reason
netty/netty pull request #13339
Opened 2023-04-17 18:22 UTC by chrisvest

Motivation:
According to RFC9113 https://datatracker.ietf.org/doc/html/rfc9113#section-8.3.1 Pseudo-header ':path' must not have empty value.

Modifications:
- Extend DefaultHttp2Headers#validateValue with validation for pseudo-header :path
- Add junit test

Result:
Pseudo-header :path with empty value results in RST_STREAM with PROTOCOL_ERROR reason.

Related to #13235, forward port of #13238

2023-04-20 13:41 UTC, normanmaurer commented
@chrisvest please fix the failing unit test and ping me once done

2023-04-27 08:17 UTC, violetagg requested changes

2023-04-27 18:48 UTC, violetagg commented
@chrisvest We need also an import
`import io.netty5.handler.codec.http.headers.HeaderValidationException;`

2023-04-27 20:02 UTC, chrisvest commented
@violetagg Ah, heck. Thanks, Violeta. It's fixed.

2023-04-28 05:04 UTC, violetagg approved these changes

2023-04-28 10:10 UTC, merged