Adapt to DirectByteBuffer constructor in Java 21
netty/netty pull request #13366
Opened 2023-04-28 12:18 UTC by luhenry

Motivation:

The signature changed between Java 20 and 21 for the DirectByteBuffer constructor.
See https://github.com/openjdk/jdk/commit/a56598f5a534cc9223367e7faa8433ea38661db9

Modification:

Simply add a check for `<init>(long, long)` on top of `<init>(long, int)`

Result:

It's able to compile and run on Java 21

2023-04-28 13:31 UTC, normanmaurer commented
@luhenry can you sign our icla: https://netty.io/s/icla ?

2023-04-28 13:34 UTC, normanmaurer requested changes

2023-04-30 20:48 UTC, luhenry commented
@normanmaurer I've signed it and updated per your review.

2023-05-01 15:17 UTC, chrisvest approved these changes

2023-05-02 06:21 UTC, normanmaurer approved these changes

2023-05-02 06:48 UTC, merged

2023-05-02 06:48 UTC, normanmaurer commented
@luhenry thanks a lot!