Rewrite DnsQueryContextManager to simplify and make it easier to debug
netty/netty pull request #13440
Opened 2023-06-13 13:33 UTC by normanmaurer

Motivation:

We are currently investigate an issue where it seems that we receive un unexpected hostname in the response. To make it easier to debug let us simplify the DnsQueryContextManager

Modifications:

- Move extra logic to internal class
- Add asserts

Result:

Cleanup

2023-06-13 17:20 UTC, hyperxpro requested changes

2023-06-13 17:20 UTC, hyperxpro commented on resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java
> +        assert self == this;
Let's add an assert message here so it's easier to debug.

2023-06-13 18:34 UTC, idelpivnitskiy approved these changes

2023-06-13 18:38 UTC, He-Pin commented
Seems like a common ground in dns querying. I have not read the code, have the questions in response been validated？

2023-06-14 05:18 UTC, hyperxpro approved these changes

2023-06-14 06:31 UTC, merged

2023-06-16 07:30 UTC, trustin reviewed
Belated LGTM. Thanks, @normanmaurer! :bow: