Handle wildcard addresses in PcapWriteHandler
netty/netty pull request #13521
Opened 2023-07-31 08:56 UTC by yawkat

Motivation:

If a UDP socket is bound to :: or 0.0.0.0, on some systems, it can still send packets to addresses of the other address family. This leads to a mismatch between the local and remote address families, that PcapWriteHandler cannot handle.

Modification:

In this scenario, coerce the local wildcard address to the wildcard address of the proper family.

Result:

Local wildcard address is handled properly and packets are logged as expected.

2023-08-16 12:20 UTC, normanmaurer requested changes

2023-08-16 12:20 UTC, normanmaurer commented on transport/src/test/java/io/netty/channel/embedded/CustomChannelId.java
> +    public CustomChannelId(int id) {
Can we keep this package private ?

2023-08-16 12:20 UTC, normanmaurer commented on handler/src/test/java/io/netty/handler/pcap/PcapWriteHandlerTest.java
> +            super(new CustomChannelId(1), false);
Just use `DefaultChannelId` so we don't need to change the visibility of `CustomChannelId`

2023-08-16 12:20 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/pcap/PcapWriteHandler.java
> +                return new InetSocketAddress("::", local.getPort());
Consider pre-creating the wildcard `InetAddress` instances and re-use them so we eliminate some overhead.

2023-08-16 12:20 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/pcap/PcapWriteHandler.java
> +                return new InetSocketAddress("0.0.0.0", local.getPort());
Same comment as above

2023-08-22 09:18 UTC, normanmaurer approved these changes

2023-08-22 09:18 UTC, merged

2023-08-22 09:18 UTC, normanmaurer commented
@yawkat want to also port this to main ?

2023-08-22 09:44 UTC, yawkat commented
@normanmaurer there's a bunch of changes we still have to port over, not just this one, ive made an issue https://github.com/netty-contrib/handler-pcap/issues/3#issuecomment-1647913199