Add support for snappy http content encoding
netty/netty pull request #13529
Opened 2023-08-06 13:11 UTC by skyguard1

Motivation:

Since netty already supports the decompression of snappy's http content encoding, it should also consider supporting snappy's http content compression

Modification:

Add support for snappy http content encoding

Result:

Netty supports snappy http content encoding

2023-08-06 13:54 UTC, franz1981 commented on codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java
> +    private final class SnappyEncoderFactory implements CompressionEncoderFactory {
static

2023-08-06 13:59 UTC, skyguard1 commented on codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java
> +    private final class SnappyEncoderFactory implements CompressionEncoderFactory {
Done

2023-08-16 12:16 UTC, normanmaurer requested changes

2023-08-16 12:16 UTC, normanmaurer commented on codec/src/main/java/io/netty/handler/codec/compression/SnappyOptions.java
> +public class SnappyOptions implements CompressionOptions {
```suggestion
public final class SnappyOptions implements CompressionOptions {
```

2023-08-16 12:16 UTC, normanmaurer commented on codec-http2/src/test/java/io/netty/handler/codec/http2/DataCompressionHttp2Test.java
> +        final ByteBuf data = Unpooled.copiedBuffer(text.getBytes());
```suggestion
        final ByteBuf data = Unpooled.copiedBuffer(text.getBytes(CharsetUtil.US_ASCII));
```

2023-08-16 12:16 UTC, normanmaurer commented on codec-http2/src/test/java/io/netty/handler/codec/http2/DataCompressionHttp2Test.java
> +        final ByteBuf data = Unpooled.copiedBuffer(text.getBytes(CharsetUtil.UTF_8.name()));
```suggestion
        final ByteBuf data = Unpooled.copiedBuffer(text.getBytes(CharsetUtil.US_ASCII)));
```

2023-08-16 23:00 UTC, skyguard1 commented on codec/src/main/java/io/netty/handler/codec/compression/SnappyOptions.java
> +public class SnappyOptions implements CompressionOptions {
Done

2023-08-16 23:00 UTC, skyguard1 commented on codec-http2/src/test/java/io/netty/handler/codec/http2/DataCompressionHttp2Test.java
> +        final ByteBuf data = Unpooled.copiedBuffer(text.getBytes());
Done

2023-08-16 23:00 UTC, skyguard1 commented on codec-http2/src/test/java/io/netty/handler/codec/http2/DataCompressionHttp2Test.java
> +        final ByteBuf data = Unpooled.copiedBuffer(text.getBytes(CharsetUtil.UTF_8.name()));
Done

2023-08-17 08:12 UTC, merged

2023-08-17 08:12 UTC, normanmaurer commented
@skyguard1 thanks a lot