[WIP] Expose DNS error code through the UnknownHostException when not NX
netty/netty pull request #13721
Opened 2023-12-08 01:51 UTC by tkountis

Motivation:

Explain here the context, and why you're making that change.
What is the problem you're trying to solve.

Modification:

Describe the modifications you've done.

Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

2023-12-08 02:08 UTC, Scottmitch commented on resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
> +                //                                domain name referenced in the query does`
nit: undo this?

2023-12-11 08:21 UTC, normanmaurer requested changes

2023-12-11 08:21 UTC, normanmaurer commented on resolver-dns/src/main/java/io/netty/resolver/dns/DnsErrorCauseException.java
> +    public DnsResponseCode getCode() {
Usually we dont use `get` prefixes... 
```suggestion
    public DnsResponseCode code() {
```

2023-12-12 16:52 UTC, bryce-anderson approved these changes

2023-12-15 06:38 UTC, normanmaurer approved these changes

2023-12-19 21:08 UTC, normanmaurer commented
@tkountis I did retry this build a few times now and it always fails during dns tests… Can you have a look if this might break something ?

2024-01-12 16:38 UTC, merged

2024-01-12 16:38 UTC, normanmaurer commented
@tkountis thanks a lot!