Add state constants for IdleStateHandler
netty/netty pull request #13802
Opened 2024-01-23 12:04 UTC by JoeCqupt

Motivation:

eliminate magic number

Modification:

Add state constants for IdleStateHandler

Result:

nothing

2024-01-23 12:05 UTC, JoeCqupt commented
@normanmaurer  PTAL

2024-01-23 12:48 UTC, hyperxpro requested changes

2024-01-23 12:48 UTC, hyperxpro commented on handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java
> +    private static final byte  ST_INITIALIZED = 1;
```suggestion
    private static final byte ST_INITIALIZED = 1;
```

2024-01-23 12:48 UTC, hyperxpro commented on handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java
> +    private static final byte  ST_DESTROYED = 2;
```suggestion
    private static final byte ST_DESTROYED = 2;
```

2024-01-23 16:31 UTC, JoeCqupt commented
> @JoeCqupt did you sign our ICLA https://netty.io/s/icla ?

I have already signed it

2024-01-24 17:48 UTC, merged

2024-01-24 17:52 UTC, normanmaurer commented
@JoeCqupt thanks a lot