[DOCUMENTATION] Make it clearer that MessageSizeEstimator is critical to get accurate backpressure
netty/netty pull request #13922
Opened 2024-03-22 14:54 UTC by chibenwa

Motivation:

Without such warning it might be tricky to get backpressure right.

Modification:

Simple documentation

Result:

Simple documentation

2024-03-22 17:02 UTC, normanmaurer requested changes

2024-03-22 17:02 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/Channel.java
> +     * {@link WriteBufferWaterMark} can be used to configure on which coundition
```suggestion
     * {@link WriteBufferWaterMark} can be used to configure on which coundition
```

2024-03-22 17:02 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/WriteBufferWaterMark.java
> + * Note that messages needs to be handled by the {@link MessageSizeEstimator}
```suggestion
 * Note that messages needs to be handled by the {@link MessageSizeEstimator}
```

2024-03-22 18:16 UTC, thc202 commented on transport/src/main/java/io/netty/channel/Channel.java
> +     * {@link WriteBufferWaterMark} can be used to configure on which coundition
```suggestion
     * {@link WriteBufferWaterMark} can be used to configure on which condition
```

2024-03-24 07:22 UTC, normanmaurer approved these changes
Thanks a lot!

2024-03-24 07:22 UTC, merged