add nio uds transport
netty/netty pull request #13965
Opened 2024-04-10 15:09 UTC by honglh

Motivation:

our use case requires using nio transport for unix-domain-socket (UDS) in netty 4.x 
PR#10991 says it is supported in 5.x and explains the complexity of doing so in 4.x.
Here, I am proposing a simpler way of adding  to 4.x using JDK16+ NIO transport. 

Modification:
Only a few APIs are overloaded to support NIO UDS class.
Most changes are added new files.

Describe the modifications you've done.
The `NioServerSocketChannel` and `NioSocketChannel` supports only INET channels. In this PR mirroring classes for NIO UDS `NioDomainServerSocketChannel` and `NioDomainSocketChannel` are added.

I modified EchoServer.java to use newly created `NioDomainServerSocketChannel` to show the difference creating a EchoServer with INET socket and with UDS socket.

Result:
This is a draft PR, so POM changes to use JDK16+ to build netty-transport are not included.

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

2024-04-12 06:56 UTC, yawkat commented
@chrisvest @normanmaurer

This patch was created by @honglh with some feedback from me. @honglh works for Oracle, though on a different team than me. They want to get the Micronaut HTTP server (and thus netty) working with domain sockets without epoll.

I will help on cleaning up this PR (commit message, compatibility, javadocs, builds, JDK version checks, CLA…) assuming you agree that the general approach is acceptable in netty 4. While this approach is not compatible with the existing kqueue and epoll domain socket implementations (this patch uses the JDK UnixDomainSocketAddress rather than the netty DomainSocketAddress that kqueue and epoll use), I think this tradeoff is reasonable to keep project layout changes to a minimum. Other than that I have no concerns with this approach.

2024-04-12 19:16 UTC, normanmaurer commented
@yawkat let me have a look and come back to you early next week

2024-04-18 14:23 UTC, normanmaurer commented
@honglh @yawkat I pushed some changes which I think makes things more correct and reduces some noise. WDYT ?

2024-04-18 16:01 UTC, yawkat commented
Thanks @normanmaurer ! Mostly looks fine to me. I've tested it locally and it works, except for the use case we already had a problem with in #13877. When directly constructing a NioDomainServerSocketChannel from a ServerSocketChannel (eg from System.inheritedChannel), and then only registering (not binding) the channel (eg systemd socket activation use case), the channel remains inactive because `bound` is never set to `true`. So we probably again either need a setter or pass in the `bound` value through the constructor.

Another nit: NioDomainServerSocketChannel vs EpollServerDomainSocketChannel, the server and domain are flipped.

2024-04-18 16:04 UTC, normanmaurer commented
@yawkat fixed the naming... let me check what we can do about the "bound" stuff here.

2024-04-19 05:16 UTC, yawkat commented
@normanmaurer the link at the bottom of https://docs.google.com/forms/d/e/1FAIpQLSfXTK6SnWWFbR50DFhoZq2floCFOUBH3kG8sZP77im5Rknctg/viewform?formkey=dG9wTmhoeGNGd1MtdFdtVXl4TlVSNlE6MQ to change the list of employees is broken

2024-04-19 06:47 UTC, normanmaurer commented
@yawkat I just pushed a commit that will allow to correctly detect if a channel was bound before. Also added some tests

2024-04-19 07:09 UTC, yawkat commented
You haven't

2024-04-19 07:15 UTC, normanmaurer commented
@yawkat 🤦 now I did :D

2024-04-19 07:24 UTC, yawkat commented
Thanks! I tried locally, and it works out of the box now. 

Otherwise this PR LGTM, we just need to get the CLA sorted on our end.

2024-04-19 09:41 UTC, normanmaurer commented
> Thanks! I tried locally, and it works out of the box now.
> 
> Otherwise this PR LGTM, we just need to get the CLA sorted on our end.

@trustin will fix it.

2024-04-19 16:41 UTC, normanmaurer commented
@chrisvest PTAL

2024-04-19 19:03 UTC, chrisvest requested changes
Looks good. I had some comments, though.

2024-04-20 13:25 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/socket/nio/NioServerDomainSocketChannel.java
> +        SocketChannel ch = javaChannel().accept();
let's just use `SocketUtils`

2024-04-20 13:25 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/socket/nio/NioServerDomainSocketChannel.java
> +        javaChannel().close();
hmm... I would think the jdk implementation would handle all of it.

2024-04-20 13:31 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/socket/nio/NioDomainSocketChannel.java
> +        }
I would keep it for now as its more "inline" with what `NioSocketChannel` does

2024-04-22 06:28 UTC, trustin commented
Thanks for your patience, @yawkat. Here's the employee list update form: https://docs.google.com/forms/d/e/1FAIpQLScnQObZBItRc5L9EC_DPB3WVdUA7K_uIgC-I7gxqq3G4JGySQ/viewform

2024-04-22 15:35 UTC, normanmaurer commented
@yawkat @honglh let me know once you think we can pull this in

2024-04-22 17:58 UTC, chrisvest commented on transport/src/main/java/io/netty/channel/socket/nio/NioServerDomainSocketChannel.java
> +        javaChannel().close();
I don't think the JDK does anything to the file path after closing a unix domain socket. At least, I can't find anything like that in the JDK source code.

2024-04-22 17:59 UTC, yawkat commented
Will do, I've sent the CLA upstairs :)

2024-04-22 18:06 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/socket/nio/NioServerDomainSocketChannel.java
> +        javaChannel().close();
Interesting... ok let me add it to make it behave the same as the native implementations

2024-04-22 18:17 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/socket/nio/NioServerDomainSocketChannel.java
> +        javaChannel().close();
@chrisvest fixed. PTAL again

2024-04-23 21:35 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/socket/nio/NioDomainSocketChannel.java
> +        config = new NioDomainSocketChannelConfig(this, socket);
How would you check that ?

2024-04-24 16:03 UTC, yawkat commented
CLA should be submitted. Note that the Oracle Point of Contact also changed.

2024-04-24 17:15 UTC, violetagg approved these changes

2024-04-26 22:25 UTC, merged

2024-04-26 22:26 UTC, normanmaurer commented
Thanks all !

2024-04-29 06:39 UTC, yawkat commented
Thanks!