build: update slf4j from 1.x to 2.0.13
netty/netty pull request #14016
Opened 2024-04-29 09:18 UTC by shoothzj

Update slf4j to 2.x. This is a backward-compatible change. 

> Log4j just update minor version. Logging configuration files don't need to change.

> SLF4J API version 2.0.0 requires Java 8 and introduces a backward-compatible fluent logging API. By backward-compatible, we mean that existing logging frameworks do not have to be changed in order for the user to benefit from the fluent logging API..

Result:

Fixes #14011

2024-04-29 09:20 UTC, slandelle requested changes
You have to upgrade logback as well.

2024-04-29 09:25 UTC, shoothzj commented
@slandelle Thanks, fixed.

2024-04-29 09:26 UTC, slandelle approved these changes

2024-04-29 09:35 UTC, violetagg commented
Please note that Logback 1.5.6 requires Java 11 at runtime
https://logback.qos.ch/news.html

2024-04-29 09:36 UTC, normanmaurer commented
hmm... not sure if we can take this then

2024-04-29 09:39 UTC, slandelle requested changes
@violetagg is right. We can only upgrade logback to 1.3.14 because of the Java 8 baseline.

2024-04-29 09:44 UTC, shoothzj commented
@normanmaurer @violetagg @slandelle change to 1.3.14 and update the description. I think we can go now.

```
## slf4j
SLF4J API version 2.0.0 requires Java 8 and introduces a backward-compatible fluent logging API. By backward-compatible, we mean that existing logging frameworks do not have to be changed in order for the user to benefit from the fluent logging API.

## logback
Version 1.3.x supports Java EE, while version 1.4.x supports Jakarta EE. The two versions are feature identical.

Both 1.3.x and 1.4.x series require SLF4J 2.0.x or later.

The 1.3.x series requires Java 8 at runtime.
```

2024-04-29 09:46 UTC, shoothzj commented
Sorry, in my most java programming work, I have been working with log4j2 most times, not familiar with logback.

2024-04-29 12:44 UTC, slandelle approved these changes

2024-04-30 16:28 UTC, merged

2024-04-30 16:39 UTC, normanmaurer commented
Thanks a lot!