Socks5 Compatible with multiple authentication methods
netty/netty pull request #14036
Opened 2024-05-06 14:02 UTC by lvxiao1

SOCKS5 encoder and decoder are both limited to only performing username password authentication. Such a design obviously violates the SRP. Whether authentication methods are supported should be handled by the application layer rather than the encoding layer. Besides, when we implement other authentication methods, we have to rewrite these decoders and encoders.

2024-05-06 16:30 UTC, chrisvest requested changes
The DefaultSocks5PasswordAuthRequest/Response are only concerned with password auth, not other auth types.

I don't think this is going in the right direction for adding support for other auth modes.

2024-05-06 16:30 UTC, chrisvest commented on codec-socks/src/main/java/io/netty/handler/codec/socksx/v5/Socks5PasswordAuthResponseDecoder.java
> +                Socks5AuthMethod authMethod = Socks5AuthMethod.valueOf(version);
`version` is not an auth mode tag

2024-05-06 16:30 UTC, chrisvest commented on codec-socks/src/main/java/io/netty/handler/codec/socksx/v5/Socks5ServerEncoder.java
> +        out.writeByte(msg.authMethod().byteValue());
No, version is always 1

2024-05-07 15:21 UTC, lvxiao1 commented
> The DefaultSocks5PasswordAuthRequest/Response are only concerned with password auth, not other auth types.
> 
> I don't think this is going in the right direction for adding support for other auth modes.

The SOCKS5 protocol does not specify messages format for other authentication methods, so it is an unpredictable variation. Removing the restriction of the authentication method being set to 1 allows for better scalability and reuse. We have a requirement that newly connected customer accounts and passwords need to be encrypted instead of using plaintext, but it also needs to be compatible with the plaintext of old customers. Therefore, there will be two different authentication methods, but the decoding and encoding behaviors are consistent.

2024-11-13 11:01 UTC, normanmaurer commented
I think we should just close this for now... @chrisvest thoughts ?

2024-11-13 17:14 UTC, closed without merging