Always send ChannelInputShutdownReadComplete in epoll
netty/netty pull request #14042
Opened 2024-05-09 17:44 UTC by chrisvest

Motivation:
We were observing EpollSocketHalfClosedTest was occasionally failing. This appears to be because we were clearing EPOLLIN too soon, and racing with getting the RDHUP where we send the ChannelInputShutdownReadComplete event.

Modification:
Delay the `clearEpollIn0()` call, so it happens as part of the ReadComplete instead of the ShutdownEvent.

Result:
There's no longer a race between the read complete and clearEpollIn.

2024-05-09 17:46 UTC, chrisvest commented
Made it a draft for now, because I can't run some of the tests in my dev container, so I don't know if this breaks anything or not.

Also, there's a commented-out piece of code that also appears to fix the EpollSocketHalfClosedTest.
I don't know which of the solutions is preferred, or if there's something else we should do.

2024-05-09 17:56 UTC, normanmaurer commented
Can you point me to the commented code that also fixes it ? Strangely enough it never fails here 🤦‍♂️🤷‍♂️

2024-05-09 18:00 UTC, chrisvest commented
> Can you point me to the commented code that also fixes it ? Strangely enough it never fails here 🤦‍♂️🤷‍♂️

This change:

https://github.com/netty/netty/pull/14042/files#diff-7ce2eb73cdfce7ee70be45a16a8a8c4412aa69dddd0cac5878068ef6afd199d4R572

2024-05-09 18:02 UTC, chrisvest commented
Without this change, it fails for me roughly one in 30 runs.

2024-05-09 18:51 UTC, normanmaurer commented
Thanks... will have a closer look tomorrow morning

2024-05-10 12:32 UTC, normanmaurer requested changes

2024-05-10 15:36 UTC, chrisvest commented on transport-classes-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java
> +//                    }
Ok. Let's see what the build says.

2024-05-10 18:08 UTC, chrisvest commented
@normanmaurer Build is happy with the change. (I think the Graal failure is something else)

2024-05-10 22:13 UTC, merged