Fix potential github action smells
netty/netty pull request #14077
Opened 2024-05-24 09:20 UTC by ceddy4395

Hey! 🙂
I've made the following changes to try and improve the github action workflows:

- Use commit hash instead of tags for action versions
  - When using a tag as version, the code related to the tag can be changed after the tag is created, whereas when using the commit hash this cannot. Therefore, for consistency and security a commit hash should be used.
- Use cache parameter instead of cache option
  - Using the cache option from the `setup/java` is easier to configure and thus less prone to mistakes. Furthermore, it makes the workflow smaller and easier to read and understand. 

(These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html))

2024-05-24 09:57 UTC, lhotari requested changes
> Use cache parameter instead of cache option
> * Using the cache option from the `setup/java` is easier to configure and thus less prone to mistakes. Furthermore, it makes the workflow smaller and easier to read and understand.
@ceddy4395 I don't think that this is relevant for this project. You are making very subjective and opinionated claims when you say "easier to configure" and "easier to read and understand". I agree that for simple projects, setting up caching for maven makes a lot of sense in the way that you suggested in this PR.

Regarding the caching, setup-java will use a fixed key of `setup-java-${{ platform }}-${{ packageManager }}-${{ fileHash }}` which is platform dependent ([docs](https://github.com/actions/setup-java?tab=readme-ov-file#caching-packages-dependencies)). A common way to configure cache action is to have multiple `restore-keys` which allows fallback to previously cached entries if there's a cache miss.

2024-05-24 10:17 UTC, ceddy4395 commented
@lhotari Thank you for the feedback, I've reverted the changes to the cache. 
What are your thoughts on the remaining changes?

2024-05-24 10:21 UTC, lhotari commented
> What are your thoughts on the remaining changes?

@ceddy4395 I don't think that using hashes is useful for official GitHub actions `actions/*`. The reason to use hashes is usually security reasons. Another reason could be to prevent regressions when the behavior of the action changes. I don't think that it's useful for official GitHub actions since the version tag is incremented for breaking changes.

In this case, I think it makes sense to use a hash for `uraimo/run-on-arch-action` because of security reasons.

2024-05-28 07:08 UTC, normanmaurer commented
I agree with @lhotari ... lets close this one

2024-05-28 07:08 UTC, closed without merging