Optimize wrap buffer cumulation in SslHandler and don't mutate input buffers
netty/netty pull request #14086
Opened 2024-05-30 12:20 UTC by lhotari

Motivation:

SslHandler doesn't support sharing the input buffers since the input buffers get mutated. This issue has been reported as #14069. Fixes have already been made to support the use case using read-only buffers as input. However, this is not useful for existing Netty applications.

I checked the Netty code once again and noticed that it's possible to optimize the current implementation in SslHandler and avoid the buffer mutation.

The default behavior in SslHandler causes very hard to debug problems. In Pulsar, there have been issues open for multiple years that have been caused by the SslHandler's default behavior of mutating the input buffers (apache/pulsar#22601 is one starting point to the issues). 

The current implementation of SslHandler will mutate the input buffers by using the input buffer as a cumulation buffer when there's available capacity. This is not optimal at all. This PR contains an improvement where the cumulation buffer is allocated to the final size immediately so that cumulation is more optimal. That's why I think that this will be more optimal in the end and won't cause performance regressions.

After these changes, it should be possible to pass a slice or duplicate of a buffer and the input buffer doesn't get mutated. The input buffer's readIndex will be modified so multiple threads cannot share the same input buffer without a slice or duplicate.

I created a failing test case that shows that a duplicate buffer doesn't prevent input buffer mutation.
![image](https://github.com/netty/netty/assets/66864/0abec333-6079-40bd-8bc1-ccfd3df6fae1)
It's a very surprising behavior of SslHandler that passing a `.retainedDuplicate()` buffer could result in mutations to the original buffer. That's another reason why I think that SslHandler shouldn't ever mutate the inputs.

Modification:

- add `protected ByteBuf composeFirst(ByteBufAllocator allocator, ByteBuf first, int bufferSize)` to AbstractCoalescingBufferQueue to support allocating an optimal cumulation buffer instead of using the input buffer as a cumulation buffer
- remove dead code from `compose` where there was handling for CompositeByteBuf
  - `composeFirst` will be called before `compose` so this case isn't needed.

Result:

Fixes #14069 without the need to set the input buffer as read-only

2024-05-31 08:28 UTC, normanmaurer requested changes

2024-05-31 08:28 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractCoalescingBufferQueue.java
> +     */
```suggestion
     * @deprecated Use {AbstractCoalescingBufferQueue#composeFirst(ByteBufAllocator, ByteBuf, int)}
     */
```

2024-05-31 08:28 UTC, normanmaurer commented on transport/src/main/java/io/netty/channel/AbstractCoalescingBufferQueue.java
> +     * @param bufferSize the optimal size of the buffer needed for cumulation
```suggestion
     * @param bufferSize the optimal size of the buffer needed for cumulation
     * @return the first buffer
```

2024-05-31 08:28 UTC, normanmaurer commented on handler/src/main/java/io/netty/handler/ssl/SslHandlerCoalescingBufferQueue.java
> +        ByteBuf newFirst;
```suggestion
        final ByteBuf newFirst;
```

2024-05-31 09:50 UTC, lhotari commented
@normanmaurer Thanks for the review. I applied your suggestions. PTAL

2024-05-31 11:57 UTC, normanmaurer approved these changes

2024-06-01 17:47 UTC, lhotari commented
The issue #12919 explains why SslHandler has been causing issues in Apache Pulsar. The incoming messages come from the network and use LengthFieldBasedFrameDecoder which slices the buffers. The buffer used by LengthFieldBasedFrameDecoder gets mutated by SslHandler later when the same buffers are passed to Apache Bookkeeper client which also uses Netty and contains SslHandler.

Issue #12919 references vert.x issue https://github.com/eclipse-vertx/vert.x/issues/4509 . It seem vert.x applied a workaround in https://github.com/eclipse-vertx/vert.x/issues/4517 .

Found also a workaround data corruption issue within Netty, #11802. That was to address #11792.

2024-06-01 17:47 UTC, lhotari commented
@franz1981 do you also have a chance to review this PR? Thanks!

2024-06-03 05:56 UTC, lhotari commented
As a followup, I also created #14093 with the title "Duplicate of slice should have the same capacity as the original slice so that it's not writable" to address the issue #12919 by @vietj, "ByteBuf slice duplicates are not slices". 
(In Pulsar, that's why SslHandler was able to corrupt the input buffer of LengthFieldBasedFrameDecoder since calling `.retainedDuplicate` later in Pulsar code "removed" the slice created by LengthFieldBasedFrameDecoder.)

2024-06-03 20:51 UTC, chrisvest approved these changes

2024-06-03 22:59 UTC, merged