Cleanup fields on AdaptiveByteBuf::deallocate
netty/netty pull request #14273
Opened 2024-09-03 08:36 UTC by franz1981

Motivation:

AdaptiveByteBuf::deallocate is not cleaning up both its wrapped ByteBuf and Chunk, extending their lifecycles (if they can be GCed) till AdaptiveByteBuf is reused again

Modifications:

Clean the relevant fields of AdaptiveByteBuf on deallocation

Result:

No more (temporary) memory leak

2024-09-03 08:42 UTC, normanmaurer requested changes
Good catch!

2024-09-03 08:58 UTC, franz1981 commented
@normanmaurer 

> you need to add a null check and throw IllegalReferenceCountException:

I've done it but still getting an ex; investigating...

2024-09-03 09:29 UTC, franz1981 commented
@normanmaurer PTAL

Not the best possible way to solve it, but I've decided to have 2 fields (in theory one was sufficient, but still...using Java Object Layout plugin for IDEA didn't show up any advantage in term of Object size...) which are "sticky" i.e. even if the object is deallocated, to respect the existing contract for `hasArray`/`hasMemoryAddress` - they become "sticky" and remember the last value, while initialized.

2024-09-04 02:17 UTC, chrisvest approved these changes

2024-09-04 06:22 UTC, merged

2024-09-04 06:39 UTC, normanmaurer commented
I already cherry-picked it

2024-09-04 07:14 UTC, franz1981 commented
u're a star, thanks bud @normanmaurer