Replace ArrayQueue with ArrayList for Recycler.LocalPool batch. (#14268)
netty/netty pull request #14292
Opened 2024-09-08 18:09 UTC by Obolrom

Motivation:

Improve performance a little bit by replacing ArrayQueue with ArrayList.

Modifications:

Replaced ArrayQueue with ArrayList for LocalPool batch.

Result:
- The new version shows better average performance for most benchmarks, especially in producerConsumer, recyclerGetAndOrphan, and unguardedProducerConsumer operations.
- Increased GC Activity: There is a tradeoff in the new version, where the garbage collection metrics (GC time, GC alloc rate) generally show increased activity in certain tests, particularly in producerConsumer and recyclerGetAndOrphan.
- Overall, the new version is better in terms of raw performance (ns/op), but you might need to consider the increased memory usage and garbage collection if it becomes a bottleneck in your application.

Fixes #14268

2024-09-08 20:00 UTC, franz1981 requested changes

2024-09-08 20:00 UTC, franz1981 commented on common/src/main/java/io/netty/util/Recycler.java
> +            DefaultHandle<T> handle = batch.isEmpty() ? null : batch.remove(0);
To use is a queue, it should have been batch.remove(batch.size() - 1)

Said that, maybe just using ArrayDeque::pollLast could be enough, looking at the implementation in the jdk repository

2024-09-08 20:01 UTC, franz1981 commented
Many thanks for your interest @Obolrom !
Did you sign already our ICLA?

2024-09-09 07:07 UTC, normanmaurer commented on common/src/main/java/io/netty/util/Recycler.java
> -            batch = new ArrayDeque<DefaultHandle<T>>(chunkSize);
yeah I think we should just use `ArrayDeque` ...

2024-09-09 07:07 UTC, normanmaurer requested changes
Please make the suggested changes

2024-09-09 07:18 UTC, Obolrom commented
@franz1981 
Thanks for the feedback. I will take a look today.
Regarding ICLA, I have signed it.

2024-09-09 16:07 UTC, Obolrom commented
## Benchmark Results and Analysis

I have conducted benchmarks for the cases:
1. **Baseline (`ArrayDeque::pollFirst`)**
2. **`ArrayDeque::pollLast`**
3. **ArrayList `batch.remove(0)`**
4. **ArrayList `batch.remove(batch.size() - 1)`**

### Benchmark Comparison

Here’s a detailed comparison of the performance and GC metrics for each of the test cases across different benchmarks:

### 1. `plainNew`
- **Baseline (`ArrayDeque::pollFirst`):** `11.526 ± 0.278 ns/op`
- **`ArrayDeque::pollLast`:** `11.433 ± 0.256 ns/op`
- **ArrayList `batch.remove(0)`:** `11.638 ± 0.189 ns/op`
- **ArrayList `batch.remove(batch.size() - 1)`:** `11.514 ± 0.167 ns/op`

**`ArrayDeque::pollLast`** is the fastest in this test, with a score of `11.433 ns/op`, slightly outperforming the baseline and other versions. Additionally, it exhibits improved GC metrics:
- **GC Time:**
  - **Baseline:** `423 ms`
  - **`ArrayDeque::pollLast`:** `398 ms`

### 2. `producerConsumer`
- **Baseline (`ArrayDeque::pollFirst`):** `125.163 ± 4.603 ns/op`
- **`ArrayDeque::pollLast`:** `125.703 ± 4.695 ns/op`
- **ArrayList `batch.remove(0)`:** `119.510 ± 11.210 ns/op`
- **ArrayList `batch.remove(batch.size() - 1)`:** `144.694 ± 3.844 ns/op`

Although **ArrayList `batch.remove(0)`** is the fastest here (`119.510 ns/op`), **`ArrayDeque::pollLast`** maintains a better balance between performance and memory consumption:
- **GC Alloc Rate:**
  - **Baseline:** `1.109 MB/sec`
  - **`ArrayDeque::pollLast`:** `1.230 MB/sec`
  - **ArrayList `batch.remove(0)`:** `12.534 MB/sec` (significantly higher, indicating more memory usage)

### 3. `recyclerGetAndOrphan`
- **Baseline (`ArrayDeque::pollFirst`):** `14.935 ± 0.401 ns/op`
- **`ArrayDeque::pollLast`:** `15.136 ± 0.573 ns/op`
- **ArrayList `batch.remove(0)`:** `13.825 ± 0.219 ns/op`
- **ArrayList `batch.remove(batch.size() - 1)`:** `13.662 ± 0.262 ns/op`

Both ArrayList methods (`batch.remove(0)` and `batch.remove(batch.size() - 1)`) perform slightly better in terms of execution time, but **`ArrayDeque::pollLast`** still shows strong memory management:
- **GC Alloc Rate:**
  - **Baseline:** `5303 MB/sec`
  - **`ArrayDeque::pollLast`:** `5237 MB/sec`
  - **ArrayList `batch.remove(0)`:** `5725 MB/sec`

**`ArrayDeque::pollLast`** also reduces GC time to `316 ms`, compared to the baseline’s `332 ms`.

### 4. `recyclerGetAndRecycle`
- **Baseline (`ArrayDeque::pollFirst`):** `15.349 ± 0.134 ns/op`
- **`ArrayDeque::pollLast`:** `15.296 ± 0.076 ns/op`
- **ArrayList `batch.remove(0)`:** `16.236 ± 0.773 ns/op`
- **ArrayList `batch.remove(batch.size() - 1)`:** `17.525 ± 1.417 ns/op`

**`ArrayDeque::pollLast`** outperforms all other versions with the best execution time of `15.296 ns/op`, and it does so with minimal GC overhead.

### 5. `unguardedProducerConsumer`
- **Baseline (`ArrayDeque::pollFirst`):** `98.373 ± 12.876 ns/op`
- **`ArrayDeque::pollLast`:** `80.781 ± 14.566 ns/op`
- **ArrayList `batch.remove(0)`:** `101.180 ± 7.570 ns/op`
- **ArrayList `batch.remove(batch.size() - 1)`:** `113.376 ± 7.215 ns/op`

In this benchmark, **`ArrayDeque::pollLast`** demonstrates a significant improvement, outperforming the baseline and other methods by a wide margin (`80.781 ns/op`):
- **GC Alloc Rate:**
  - **Baseline:** `4.808 MB/sec`
  - **`ArrayDeque::pollLast`:** `1.315 MB/sec`

It makes **`ArrayDeque::pollLast`** the most efficient in terms of performance but in terms of memory usage as well.

---
### TLDR; Conclusion

The **`ArrayDeque::pollLast`** version offers a balanced solution across all benchmarks, providing:
- The best overall performance in benchmarks such as `plainNew`, `recyclerGetAndRecycle`, and `unguardedProducerConsumer`.
- A significant reduction in GC time, improving memory efficiency across most tests.
  
It seems **`ArrayDeque::pollLast`** is the optimal choice due to its balanced approach to both performance and resource management.

@franz1981 @normanmaurer what do you think?

2024-09-09 16:15 UTC, franz1981 commented
I'm curious about

```
5. unguardedProducerConsumer
Baseline (ArrayDeque::pollFirst): 98.373 ± 12.876 ns/op
ArrayDeque::pollLast: 80.781 ± 14.566 ns/op
```
can you verify it more e.g.

by running `-prof perfnorm` (if you're on linux) and publishing the counters there.

Consider that the case where it should grant benefit(s) is with this process:
1. N buffers allocated (and not released)
2. N buffers released (the ones allocated before)
3. 1 keep on been acquired and released 

1 and 2 should be performed in the setup phase and are meant to populate the local queue of N entries.
3 should 
- with `pollFirst`: acquiring from the head, and releasing to the tail - basically iterating the previously populated entries in the local pool
- with `pollLast`: acquiring and releasing the head -> which means reusing the same buffer over and over

2024-09-09 18:36 UTC, Obolrom commented
@franz1981
Regarding your last comment, I’m not sure I fully understand what needs to be done.

Do we need to configure the `RecyclerBenchmark` this way?
```java
protected ChainedOptionsBuilder newOptionsBuilder() throws Exception {
     return super.newOptionsBuilder().addProfiler("gc").addProfiler(LinuxPerfNormProfiler.class);
}
```
It provides a huge output with about 150 lines.

Or are we supposed to write a new benchmark from scratch?

2024-09-09 19:14 UTC, chrisvest approved these changes
+1 on using `ArrayDeque::pollLast`. Algorithmically it makes the most sense.
Please update the PR description to match the changes.

2024-09-10 13:59 UTC, normanmaurer commented
@franz1981 please pull in once satisfied .

2024-09-10 14:07 UTC, franz1981 commented
@Obolrom no worries for the benchmarks - in this case can be done later, because TBH the change is just the "right thing" - as @chrisvest said ;) well done!!

2024-09-10 14:08 UTC, franz1981 approved these changes
LGTM and well done picking the issue :)

cannot wait for more!

2024-09-10 14:48 UTC, normanmaurer approved these changes
Maybe just consider adding a comment why we use `pollLast()`

2024-09-13 06:22 UTC, merged