reduce memory fragmentation
netty/netty pull request #14333
Opened 2024-09-13 16:11 UTC by CLFutureX

Motivation:
  
1. Currently, when allocating from a magazine, if the remaining memory of the current chunk is not enough for allocation,
   the chunk is directly released.
   If the size to be allocated at this time is greater than the remaining memory of the chunk but >= RETIRE_CAPACITY, direct release will result in significant memory fragmentation.

2. When transferring the current chunk, if the transfer to the central queue ultimately fails, the chunk is chosen to be released.

Modification:
1. In this scenario, consider transferring the chunk to the nextInLine.

2. When transferring the chunk, if the transfer to the central queue still fails, consider comparing it with the local nextInLine and retiring the smaller one.

2024-09-13 17:14 UTC, franz1981 commented
I like the idea of not wasting it - well done!

2024-09-13 21:22 UTC, chrisvest commented
The "trans result" int and interface is unnecessary, because we only make a single boolean decision based on it.
Please try to simplify the change before I look at it further, as I think this is more complicated than it needs to be.

2024-09-14 14:11 UTC, CLFutureX commented
> The "trans result" int and interface is unnecessary, because we only make a single boolean decision based on it.
> Please try to simplify the change before I look at it further, as I think this is more complicated than it needs to be.

Well, to avoid picking up a chunk that was just put into nextInLine or the central queue, the TRAN_RESULT class was added at the time. Now, by readjusting the order to get before putting, the issue can be resolved.

2024-09-16 09:52 UTC, normanmaurer requested changes
I like the idea... Just some nits related to naming the method

2024-09-16 09:52 UTC, normanmaurer commented on buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> +        private void transChunk(Chunk current) {
```suggestion
        private void transferChunk(Chunk current) {
```

2024-09-16 09:52 UTC, normanmaurer commented on buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> +                        transChunk(newChunk);
```suggestion
                        transferChunk(newChunk);
```

2024-09-16 09:52 UTC, normanmaurer commented on buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> +                    transChunk(last);
```suggestion
                    transferChunk(last);
```

2024-09-16 11:46 UTC, CLFutureX commented
> I like the idea... Just some nits related to naming the method

Thanks for your suggestion，its great

2024-09-16 11:52 UTC, normanmaurer approved these changes
LGTM

2024-09-16 11:53 UTC, normanmaurer commented
@chrisvest PTAL

2024-09-16 14:16 UTC, franz1981 commented on buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> +            if (current.remainingCapacity() > nextChunk.remainingCapacity()) {
yess

2024-09-16 16:04 UTC, chrisvest commented on buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> +            if (current.remainingCapacity() > nextChunk.remainingCapacity()) {
The magazine should have exclusive access to the nextInLine chunks, so this should not be a problem to access the chunk. However, with #14334 I think it'll be possible for the `NEXT_IN_LINE.compareAndSet` to fail and for the `NEXT_IN_LINE.get` to then return `null`, so it'd be good to have a null-check here.

2024-09-16 16:08 UTC, normanmaurer commented on buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> +            if (current.remainingCapacity() > nextChunk.remainingCapacity()) {
Good point ... @CLFutureX please add a null check as @chrisvest suggested

2024-09-17 02:48 UTC, CLFutureX commented on buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> +            if (current.remainingCapacity() > nextChunk.remainingCapacity()) {
Good suggestion, I've added it

2024-09-17 14:10 UTC, normanmaurer approved these changes
LGTM

2024-09-18 14:17 UTC, merged

2024-09-18 14:17 UTC, normanmaurer commented
@CLFutureX thanks a lot!

2024-09-18 14:47 UTC, normanmaurer commented
I think we also want to port this to main... @chrisvest WDYT ?

2024-09-18 17:15 UTC, chrisvest commented
@normanmaurer I agree.

2024-09-18 17:52 UTC, normanmaurer commented
@CLFutureX you want to do a PR against main ?

2024-09-18 23:44 UTC, CLFutureX commented
@normanmaurer  with pleasure,i will do it later