Fix：RunAllTasks should be implemented by passing the number of tasks
netty/netty pull request #14542
Opened 2024-12-06 12:08 UTC by dreamlike-ocean

Motivation:

RunAllTasks should be implemented by passing the number of tasks to run, rather than using a timeout

Modification:

Add an override method to handle running all tasks correctly

Result:

https://github.com/netty/netty/issues/14165

2024-12-06 13:25 UTC, franz1981 commented
> RunAllTasks should be implemented by passing the number of tasks to run, rather than using a timeout

duration of such tasks is not known, some could be long, other shorts; why you want to use the number of tasks?

2024-12-06 13:37 UTC, dreamlike-ocean commented
> > RunAllTasks should be implemented by passing the number of tasks to run, rather than using a timeout
> 
> duration of such tasks is not known, some could be long, other shorts; why you want to use the number of tasks?

I have checked the code of SingleThreadIoEventLoop::run. 
If the code uses a timeout, the default value might not be enough. Therefore, I believe the intention of the code is to specify the number of tasks to run.

Do you have any better ideas

``` java
    @Override
    protected void run() {
        assert inEventLoop();
        do {
            runIo();
            if (isShuttingDown()) {
                ioHandler.prepareToDestroy();
            }
            runAllTasks(maxTasksPerRun);

            // We should continue with our loop until we either confirmed a shutdown or we can suspend it.
        } while (!confirmShutdown() && !canSuspend());
    }
```

```java

protected static final int DEFAULT_MAX_TASKS_PER_RUN = Math.max(1,
            SystemPropertyUtil.getInt("io.netty.eventLoop.maxTaskPerRun", 1024 * 4))

```

2024-12-11 13:53 UTC, normanmaurer commented
@dreamlike-ocean I think you are correct here.

2024-12-11 13:55 UTC, normanmaurer requested changes

2024-12-11 13:55 UTC, normanmaurer commented on common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java
> +            if (task == null || runTasks >= maxTasksPerRun) {
```suggestion
            if (task == null || runTasks == maxTasksPerRun) {
```

2024-12-11 13:55 UTC, normanmaurer commented on common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java
> +    protected boolean runAllTasks(int maxTasksPerRun) {
Let's rename it to something like this and call it from `SingleThreadIoEventLoop`.
```suggestion
    protected boolean runAllTasksWithLimit(int maxTasksPerRun) {
```

2024-12-11 13:57 UTC, normanmaurer commented
Or wait... I think we should better fix it by using a timeout like @franz1981 suggested. Will do a PR shortly

2024-12-12 07:14 UTC, normanmaurer commented
Closed in favor of https://github.com/netty/netty/pull/14557

2024-12-12 07:14 UTC, closed without merging