Fix classloader leaks in GlobalEventExecutor
netty/netty pull request #14616
Opened 2024-12-23 18:02 UTC by chrisvest

Motivation:
If Netty is on a main classpath in a system that creates ephemeral classloaders, e.g. for plug-ins, then we should avoid holding on to those ephemeral classloaders.

Modification:
Clear the stack trace in the GlobalEventExecutor termination future, because the stack trace would hold on to class which in turn hold on to class loaders, and it would hold on to an ephemeral classloader if the GEE was first initialized by code in an ephemeral classloader.

Also avoid holding on to context classloaders through the Thread.inheritedAccessControlContext when starting the GEE thread.

Result:
Classloader leaks should be fix.

Fixes #14615

2024-12-23 18:18 UTC, normanmaurer requested changes

2024-12-23 18:18 UTC, normanmaurer commented on common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java
> +            setContextClassLoader(Thread.currentThread(), null);
```suggestion
            Thread current = Thread.currentThread();
            ClassLoader parentCCL = current.getContextClassLoader();
            setContextClassLoader(current, null);
```

2024-12-23 18:18 UTC, normanmaurer commented on common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java
> +                setContextClassLoader(Thread.currentThread(), parentCCL);
```suggestion
                setContextClassLoader(current, parentCCL);
```

2024-12-23 18:18 UTC, franz1981 commented
@gsmet as well :)

2024-12-24 07:16 UTC, normanmaurer approved these changes

2024-12-25 18:02 UTC, merged